Switch to GitHub actions
drud/ddev pull request #2615
Opened 2020-11-07 14:45 UTC by dennisameling

As discussed in/closes https://github.com/drud/ddev/issues/2604

2020-11-07 14:54 UTC, rfay commented
Completely amazing! Thanks!

I rebased this and restored the files in the .buildkite directory, as we want those tests to run until we have replacements.

2020-11-07 14:55 UTC, rfay commented
It seems we need to enable the github actions on the drud/ddev repo though right?

2020-11-07 14:56 UTC, dennisameling commented
Think so, yes, an option could be to have a branch `switch-to-github-actions` directly on the `drud/ddev` repo instead of my fork, that will enable GH Actions as well.

2020-11-07 14:59 UTC, rfay commented
Do we have to add to the action to run on pull request? as https://github.community/t/run-a-github-action-on-pull-request-for-pr-opened-from-a-forked-repo/16054 ?

2020-11-07 15:01 UTC, rfay commented
Maybe it's because of
```
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
```
?

2020-11-07 15:04 UTC, rfay commented
* On using golang directly: Maybe the day has come. It would make everything faster.  Thinking.

I absolutely can't believe you got so much done on this.

2020-11-07 15:05 UTC, rfay commented
If the only workaround to get the actions to run on drud/ddev is a branch on drud/ddev, I'll set it up. Let me know if that's what we need to do.

2020-11-07 15:07 UTC, rfay commented
The build-time permissions issues are the result of trying to mkdir /workdir (in root), which I don't think can ever work. I'll look, but I think that has been worked around in the other builders for quite a while, not sure why it's trying to do that here. I think missing environment variable. Time for breakfast, will look after.

2020-11-07 15:17 UTC, rfay commented
Oh, on circleci, if you have a test enabled on a fork, it doesn't run on the target repo, which makes sense because it doesn't make sense to have two tests going at once. Could that be going on here?

We certainly don't want to lose the ability to test forked PRs in general.

2020-11-07 15:32 UTC, rfay commented
The permissions thing seems to be that the container is somehow not running as the same user as the files it's mounting?

```
docker run -t --rm -u 501:20 -v "//Users/rfay/workspace/ddev://workdir:cached" -e GOPATH="//workdir/.gotmp" -e GOCACHE="//workdir/.gotmp/.cache" -e GOFLAGS="" -e CGO_ENABLED=0 -w //workdir golang:1.15.3
```

The cache dir has already been created on the host in 
```
mkdir -p .gotmp/{.cache,pkg,src,bin/$TARGET}
``` 

And it should be writeable. But I pushed https://github.com/drud/ddev/pull/2615/commits/0dfdc01d5828fcb79a7ce4bbb6c6133ea9c1e2fd to make sure it is.

2020-11-07 15:44 UTC, rfay commented
I do see that the actions are running in [your fork](https://github.com/dennisameling/ddev/tree/switch-to-github-actions0) so that's probably fine for now. I would assume that after the actions *land* they get run on forked PRs. Or we'll figure that out.

2020-11-07 17:21 UTC, dennisameling commented
Yeah, GH Actions has to be enabled once by landing the config in `master`, then it'll run on PRs as well 👍

2020-11-07 18:12 UTC, rfay commented
I guess my one question would be... how do you fix up tests in a PR? Should the github actions be in a separate repo?

2020-11-07 21:59 UTC, dennisameling commented
Not sure if I understand the question correctly, but once GH Actions is activated on the `master` branch, and tests are failing, you can update the GH Actions config using any PR, just like you would with Travis/CircleCI/etc. - it just doesn't trigger yet as long as there's no files in `.github/workflows` on the `master` branch. 

So for now, we have two possible ways forward:
1. Keep pushing commits to this PR and check the GH Actions progress on https://github.com/dennisameling/ddev/actions
2. Create a new branch in `drud/ddev` directly to add a GH Actions config, then create a PR for that branch to the `master` branch and tests will start to run automatically, then on subsequent commits GH Actions will trigger again 👍

2020-11-07 22:27 UTC, rfay commented
I'm fine with continuing and just checking the results in https://github.com/dennisameling/ddev/actions

Another technique we could use: Why don't you create a trivial github actions .github/workflows PR that does not much... and We'll pull it. Then this one can be rebased and we'll be fine.

2020-11-07 22:30 UTC, dennisameling commented
Sure, sounds good! Will create a PR for that tomorrow morning 👍🏼

2020-11-08 14:49 UTC, dennisameling commented
Here we have it! GH Actions in the "checks" section! 🚀

2020-11-08 14:50 UTC, rfay commented
Yay!

2020-11-08 16:41 UTC, dennisameling commented
**Debugging**
I've configured `tmate` on Ubuntu for easier troubleshooting (https://github.com/marketplace/actions/debugging-with-tmate).
You can SSH into the container, and run any commands you want. When you're done, you can run `touch continue` and the GH Actions job will continue as normal 🚀 

**ubuntu-20.04 - make testcmd - Router problem**:
From a previous run: https://github.com/drud/ddev/runs/1370506832

I was able to SSH into the GH Actions VM thanks to `tmate` and run `docker logs ddev-router`:
```
runner@fv-az183-600:~/work/ddev/ddev$ docker logs ddev-router
Using the local CA at "/root/.local/share/mkcert" ✨
The local CA is now installed in the system trust store! ⚡

Using the local CA at "/root/.local/share/mkcert" ✨

Created a new certificate valid for the following names 📜
 - "*.ddev.local"
 - "*.ddev.site"
 - "127.0.0.1"
 - "localhost"
 - "ddev-router"
 - "ddev-router.ddev_default"

Reminder: X.509 wildcards only go one level deep, so this won't match a.b.ddev.local ℹ️

The certificate is at "/etc/nginx/certs/.crt" and the key at "/etc/nginx/certs/.key" ✅

Using the local CA at "/root/.local/share/mkcert" ✨

Created a new certificate valid for the following names 📜
 - "*.ddev.local"
 - "*.ddev.site"
 - "ddev-router"
 - "ddev-router.ddev_default"
 - "127.0.0.1"
 - "localhost"

Reminder: X.509 wildcards only go one level deep, so this won't match a.b.ddev.local ℹ️

The certificate is at "/etc/nginx/certs/master.crt" and the key at "/etc/nginx/certs/master.key" ✅

forego     | starting nginx.1 on port 5000
forego     | starting dockergen.1 on port 5100
dockergen.1 | 2020/11/08 15:44:34 Generated '/gen-cert-and-nginx-config.sh' from 4 containers
dockergen.1 | 2020/11/08 15:44:34 Running 'bash /gen-cert-and-nginx-config.sh'
dockergen.1 | 2020/11/08 15:44:36 [bash /gen-cert-and-nginx-config.sh]: Processing certs and nginx for hostnames: testcmdwordpress.ddev.site
dockergen.1 | 2020/11/08 15:44:36 [bash /gen-cert-and-nginx-config.sh]:  - "testcmdwordpress.ddev.site"
dockergen.1 | 020/11/08 15:44:36 [bash /gen-cert-and-nginx-config.sh]: 2020/11/08 15:44:36 [sleep 1 && nginx -s reload]: 2020/11/08 15:44:36 [emerg] 997#997: no servers are inside upstream in /etc/nginx/conf.d/default.conf:92
dockergen.1 | 2020/11/08 15:44:36 Contents of /gen-cert-and-nginx-config.sh did not change. Skipping notification 'bash /gen-cert-and-nginx-config.sh'
```

Could this be related to the fact that GH Actions by default is running some custom Docker build (19.03.13+azure)? What do you think?

```
Client:
 Version:           19.03.13+azure
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        cd8016b6bcc51a51f577bcffb37e6a870f7813f9
 Built:             Tue Sep 15 23:02:04 2020
 OS/Arch:           linux/amd64
 Experimental:      true

Server:
 Engine:
  Version:          19.03.13+azure
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       bd33bbf0497b2327516dc799a5e541b720822a4c
  Built:            Mon Mar 12 00:00:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7+azure
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.18.0
  GitCommit:        
~/work/ddev/ddev/containers/ddev-dbserver ~/work/ddev/ddev
```

**macos-latest - make testcmd - failing tests**:
See https://github.com/drud/ddev/runs/1370593932?check_suite_focus=true
```
--- FAIL: TestComposerCmd (50.44s)
--- FAIL: TestDebugNFSMount (0.76s)
--- FAIL: TestCmdExec (11.47s)
--- FAIL: TestCmdExportDB (30.80s)
--- FAIL: TestCmdImportDB (20.16s)
--- FAIL: TestShareCmd (1.07s)
--- FAIL: TestCmdAuthSSH (29.10s)
```

**ubuntu-20.04 - container tests - ddev-dbserver**:
https://github.com/drud/ddev/runs/1370506952
```
#12 0.525 Starting mysqld --skip-networking
#12 0.543 201108 15:07:41 [Note] mysqld (mysqld 5.5.64-MariaDB-1~trusty) starting as process 65 ...
#12 0.563 201108 15:07:41 InnoDB: The InnoDB memory heap is disabled
#12 0.563 201108 15:07:41 InnoDB: Mutexes and rw_locks use GCC atomic builtins
#12 0.563 201108 15:07:41 InnoDB: Compressed tables use zlib 1.2.8
#12 0.563 201108 15:07:41 InnoDB: Using Linux native AIO
#12 0.569 201108 15:07:41 InnoDB: Initializing buffer pool, size = 128.0M
#12 0.575 201108 15:07:41 InnoDB: Completed initialization of buffer pool
#12 0.580 InnoDB: The first specified data file ./ibdata1 did not exist:
#12 0.580 InnoDB: a new database to be created!
#12 0.580 201108 15:07:41  InnoDB: Setting file ./ibdata1 size to 10 MB
#12 0.580 InnoDB: Database physically writes the file full: wait...
#12 0.689 201108 15:07:41  InnoDB: Log file ./ib_logfile0 did not exist: new to be created
#12 0.689 InnoDB: Setting log file ./ib_logfile0 size to 5 MB
#12 0.689 InnoDB: Database physically writes the file full: wait...
#12 0.780 201108 15:07:41  InnoDB: Log file ./ib_logfile1 did not exist: new to be created
#12 0.780 InnoDB: Setting log file ./ib_logfile1 size to 5 MB
#12 0.780 InnoDB: Database physically writes the file full: wait...
#12 0.832 InnoDB: Doublewrite buffer not found: creating new
#12 0.875 InnoDB: Doublewrite buffer created
#12 1.031 InnoDB: 127 rollback segment(s) active.
#12 1.032 InnoDB: Creating foreign key constraint system tables
#12 1.037 InnoDB: Foreign key constraint system tables created
#12 1.037 201108 15:07:42  InnoDB: Waiting for the background threads to start
#12 2.043 201108 15:07:43 Percona XtraDB (http://www.percona.com) 5.5.61-MariaDB-38.13 started; log sequence number 0
#12 2.043 201108 15:07:43 [Note] Plugin 'FEEDBACK' is disabled.
#12 2.043 201108 15:07:43 [Note] Event Scheduler: Loaded 0 events
#12 2.043 201108 15:07:43 [Note] mysqld: ready for connections.
#12 2.043 Version: '5.5.64-MariaDB-1~trusty'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  mariadb.org binary distribution
#12 91.96 MariaDB initialization startup process timed out.
#12 ERROR: executor failed running [/bin/sh -c /create_base_db.sh;]: runc did not terminate sucessfully
------
 > [8/13] RUN /create_base_db.sh;:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c /create_base_db.sh;]: runc did not terminate sucessfully
make: *** [Makefile:18: mariadb_containers] Error 1
```

What I find weird about this one is that the server is running at `/var/run/mysqld/mysqld.sock`, but when I try locally (and in CircleCI) it's running on `/var/tmp/mysql.sock`. Do you have any tips regarding this?

I won't have more time in the coming days to look into this unfortunately; please feel free to dive into this and commit things to my branch. Hope the debugging with `tmate` helps!

2020-11-09 18:36 UTC, rfay commented
SO much appreciating your work on this. I don't think I'll have a chance to work on it this week because of release of v1.16 and a big 3-day meeting. But PROGRESS!

2020-11-10 11:16 UTC, dennisameling commented
Cool - I did a few more things but now really don't have any more time this week 😊 

Was able to fix some container tests by forcing the socket using `mysqld --socket=$SOCKET` and some config changes in MacOS.

MariaDB 5.5 is consistently failing on Linux due to a problem with the `innodb_log_file_size`. For now I've skipped MariaDB 5.5 altogether to see how far we can get with the other container tests. Interestingly, MySQL 5.5 works without any problems.

```
#12 2.047 Version: '5.5.64-MariaDB-1~trusty'  socket: '/var/tmp/mysql.sock'  port: 0  mariadb.org binary distribution
#12 2.546 mysqld is alive
#12 2.937 Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
#12 4.156 /usr/bin/xtrabackup
#12 4.218 201110 10:54:24  version_check Connecting to MySQL server with DSN 'dbi:mysql:;mysql_read_default_group=xtrabackup;port=3306;mysql_socket=/var/tmp/mysql.sock' as 'root'  (using password: YES).
#12 4.220 201110 10:54:24  version_check Connected to MySQL server
#12 4.220 201110 10:54:24  version_check Executing a version check against the server...
#12 4.221 201110 10:54:24  version_check Done.
#12 4.222 201110 10:54:24 Connecting to MySQL server host: localhost, user: root, password: set, port: 3306, socket: /var/tmp/mysql.sock
#12 4.225 Using server version 5.5.64-MariaDB-1~trusty
#12 4.225 xtrabackup version 2.3.10 based on MySQL server 5.6.24 Linux (x86_64) (revision id: bd0d4403f36)
#12 4.225 xtrabackup: uses posix_fadvise().
#12 4.225 xtrabackup: cd to /var/lib/mysql
#12 4.225 xtrabackup: open files limit requested 65535, set to 1048576
#12 4.225 xtrabackup: using the following InnoDB configuration:
#12 4.225 xtrabackup:   innodb_data_home_dir = ./
#12 4.225 xtrabackup:   innodb_data_file_path = ibdata1:10M:autoextend
#12 4.225 xtrabackup:   innodb_log_group_home_dir = ./
#12 4.225 xtrabackup:   innodb_log_files_in_group = 2
#12 4.225 xtrabackup:   innodb_log_file_size = 50331648
#12 4.225 2020-11-10 10:54:24 7fd77efc5780 InnoDB: Using Linux native AIO
#12 4.228 InnoDB: Error: log file ./ib_logfile0 is of different size 5242880 bytes
#12 4.228 InnoDB: than specified in the .cnf file 50331648 bytes!
#12 ERROR: executor failed running [/bin/sh -c /create_base_db.sh]: runc did not terminate sucessfully
```

To be continued later!

2020-11-10 12:29 UTC, rfay commented
I've seen the "InnoDB: Error: log file ./ib_logfile0 is of different size 5242880 bytes" only in real servers before (not in places like this). It's usually caused by changing the config, and usually fixed by deleting the log file. But that would mean that the ib_logfile0 is sitting there when we're trying to build the base db... but it shouldn't exist yet.

2020-11-10 14:15 UTC, dennisameling commented
Found the issue (`tmate` has been incredibly useful in debugging through SSH). In the Docker image, `/etc/my.cnf` is not being read at all. Therefore things like `socket = /var/tmp/mysql.sock` and `innodb-log-file-size = 48M` aren't configured, leading to those errors.

For now, I manually added the socket and innodb_log_file_size configs to `create_base_db.sh`, which fixes the MariaDB 5.5 issue:

```
mysqld --user=root --socket=$SOCKET --innodb_log_file_size=48M
```

The weird thing is that `/etc/my.cnf` exists in the container, but when I try to run `mysqld --defaults-file=/etc/my.cnf` I get the following error:

```
#12 0.507 Starting mysqld --skip-networking --socket=/var/tmp/mysql.sock
#12 0.520 Could not open required defaults file: /etc/my.cnf
#12 0.520 Fatal error in defaults handling. Program aborted
#12 1.515 MariaDB initialization startup failed
#12 ERROR: executor failed running [/bin/sh -c /create_base_db.sh]: runc did not terminate sucessfully
```

Things like chmodding that file to 644 don't work. The container can read the file, but somehow MariaDB can't read it.

At least for now we have working container tests 🎉 let's investigate this further some time next week

2020-11-17 02:52 UTC, rfay commented
Rebased

2020-11-19 11:13 UTC, dennisameling commented
@rfay I think I can make some time this weekend to continue work on this. Shall I first focus on moving everything from CircleCI to GH Actions (Linux workloads)? Looks like that's the easiest one to start with. Just to be sure, we need the following workloads, right?

- lx_container_test (already working in GH Actions ✔️)
- build
  - lx_nginx_fpm_test
  - lx_apache_fpm_test
  - lx_nfsmount_test
- nightly_build
- release_build

2020-11-19 13:03 UTC, rfay commented
Yes, those are fantastic tasks. Along the way, but probably later (but best to keep in view) we have to push images like we do in https://github.com/drud/ddev/issues/2617. In a perfect world, we would build the images for every test, or at least when the code had changed, but that would make tests take even longer, which just doesn't seem do-able. It *might* be possible to push only when they changed though, not sure how the tracking in pkg/version/version.go could be done in that case. 

Thanks so much for the incredible work on this!

2020-11-19 13:04 UTC, rfay commented
I had hoped to spend some time on it myself, but have been pretty much used up by post-release tasks, cleanup and support :( Love the progress though!

2020-11-19 22:01 UTC, dennisameling commented
I think it's feasible to build the images; they are being built anyway in `lx_container_test`.

One thing that we could do though, is that instead of pushing those images to Docker Hub, we store them as CI artifacts (Docker buildx supports writing tarballs to disk) and then download them in a later stage to test against them. How does that sound? 

I did a similar thing for Mautic, where we upload the released package and then test against it in the next step:

https://github.com/mautic/mautic/blob/staging/.github/workflows/release.yml#L88-L98

2020-11-19 22:06 UTC, rfay commented
The general strategy of building-and-storing could work for the test, but the time cost of waiting so long for the image builds before starting the functional tests is the problem. But it certainly works for release build.

2020-11-20 23:01 UTC, dennisameling commented
I've done some optimizations to the container tests file. The tests now run in parallel. Have also done some tweaks to the `dbserver` Dockerfile to speed up builds (saves 30-50 seconds per db image build in my testing! With 11 db images, that adds up 🕐 )

### Only triggering container tests when something _actually_ has changed
When someone creates a pull request, the container tests are only triggered when one or more files have changed in the `containers/` directory, e.g. when we update a `Dockerfile`. AFAIK there's no need to run container tests on **every** PR.

When a commit is created in the `master` branch, the container tests are always triggered, just to be sure. But this can also be configured differently if you want.

https://github.com/drud/ddev/blob/7c9bc8802e546c067cdb00da81885eab6190ca44/.github/workflows/container-tests.yml#L3-L10

2020-11-21 20:30 UTC, dennisameling commented
@rfay the build of executables works now (https://github.com/drud/ddev/pull/2615/checks?check_run_id=1435919804), but I'm currently stuck on running the tests on Linux (`make test`). I SSHed into the test VM by using `tmate` and managed to get the logs below. Do you have any ideas/tips what I can do to troubleshoot further?

```
runner@fv-az180-364:~/work/ddev/ddev/.gotmp/bin/linux_amd64/dennistest$ ../ddev start
Could not check for updates. This is most often caused by a networking issue.
Starting dennistest...
Pushed mkcert rootca certs to ddev-global-cache/mkcert
Running  Command=ip address show dev docker0
Creating volume "dennistest-mariadb" with default driver
Building db
Building web
Creating ddev-dennistest-db ... done
Creating ddev-dennistest-web ... done
Creating ddev-dennistest-dba ... done

Creating ddev-router ... done

Failed to start dennistest: ddev-router failed to become ready; debug with 'docker logs ddev-router'; logOutput=, err=health check timed out: labels map[com.docker.compose.service:ddev-router] timed out without becoming healthy, status=
```

```
runner@fv-az180-364:~/work/ddev/ddev/.gotmp/bin/linux_amd64/dennistest$ docker logs ddev-router
Using the local CA at "/root/.local/share/mkcert" ✨
The local CA is now installed in the system trust store! ⚡

Using the local CA at "/root/.local/share/mkcert" ✨

Created a new certificate valid for the following names 📜
 - "*.ddev.local"
 - "*.ddev.site"
 - "127.0.0.1"
 - "localhost"
 - "ddev-router"
 - "ddev-router.ddev_default"

Reminder: X.509 wildcards only go one level deep, so this won't match a.b.ddev.local ℹ️

The certificate is at "/etc/nginx/certs/.crt" and the key at "/etc/nginx/certs/.key" ✅

Using the local CA at "/root/.local/share/mkcert" ✨

Created a new certificate valid for the following names 📜
 - "*.ddev.local"
 - "*.ddev.site"
 - "ddev-router"
 - "ddev-router.ddev_default"
 - "127.0.0.1"
 - "localhost"

Reminder: X.509 wildcards only go one level deep, so this won't match a.b.ddev.local ℹ️

The certificate is at "/etc/nginx/certs/master.crt" and the key at "/etc/nginx/certs/master.key" ✅

forego     | starting nginx.1 on port 5000
forego     | starting dockergen.1 on port 5100
dockergen.1 | 2020/11/21 16:10:17 Generated '/gen-cert-and-nginx-config.sh' from 4 containers
dockergen.1 | 2020/11/21 16:10:17 Running 'bash /gen-cert-and-nginx-config.sh'
dockergen.1 | 2020/11/21 16:10:18 [bash /gen-cert-and-nginx-config.sh]: Processing certs and nginx for hostnames: dennistest.ddev.site
dockergen.1 | 2020/11/21 16:10:18 [bash /gen-cert-and-nginx-config.sh]:  - "dennistest.ddev.site"
dockergen.1 | /21 16:10:18 [bash /gen-cert-and-nginx-config.sh]: 2020/11/21 16:10:18 [sleep 1 && nginx -s reload]: 2020/11/21 16:10:18 [emerg] 997#997: no servers are inside upstream in /etc/nginx/conf.d/default.conf:92
dockergen.1 | 2020/11/21 16:10:18 Watching docker events
dockergen.1 | 2020/11/21 16:10:18 Contents of /gen-cert-and-nginx-config.sh did not change. Skipping notification 'bash /gen-cert-and-nginx-config.sh'
```

`docker ps` shows the following:

```
CONTAINER ID        IMAGE                                                              COMMAND                  CREATED             STATUS                   PORTS                                                                                                                  NAMES
ca64d1c329c8        drud/ddev-router:v1.16.0                                           "/app/docker-entrypo…"   4 hours ago         Up 4 hours (unhealthy)   127.0.0.1:80->80/tcp, 127.0.0.1:443->443/tcp, 127.0.0.1:8025-8026->8025-8026/tcp, 127.0.0.1:8036-8037->8036-8037/tcp   ddev-router
685ec4b85f4e        phpmyadmin:5                                                       "/docker-entrypoint.…"   4 hours ago         Up 4 hours               0.0.0.0:32774->80/tcp                                                                                                  ddev-dennistest-dba
cda3b380cdb8        drud/ddev-webserver:20201116_drush_launcher_074-dennistest-built   "/start.sh"              4 hours ago         Up 4 hours (healthy)     8025/tcp, 127.0.0.1:32780->80/tcp, 127.0.0.1:32779->443/tcp                                                            ddev-dennistest-web
eed41abf7e61        drud/ddev-dbserver-mariadb-10.2:v1.16.0-dennistest-built           "/docker-entrypoint.…"   4 hours ago         Up 4 hours (healthy)     127.0.0.1:32778->3306/tcp                                                                                              ddev-dennistest-db
3c9cae44028f        drud/ddev-ssh-agent:v1.16.0-built                                  "/entry.sh ssh-agent"    4 hours ago         Up 4 hours (healthy)                                                                                                                            ddev-ssh-agent
```

2020-11-21 20:58 UTC, dennisameling commented
Found something. If I look into the `ddev-router` container and open `/etc/nginx/conf.d/default.conf`, there isn't anything in the upstream:

```
    # dennistest.ddev.site
    upstream dennistest.ddev.site-80 {
    keepalive 100;
    }
    # dennistest.ddev.site
    upstream dennistest.ddev.site-8025 {
    keepalive 100;
    }
    # dennistest.ddev.site
    upstream dennistest.ddev.site-8036 {
    keepalive 100;
    }
```

If I compare that to a local running project on my local machine, that looks like:

```
    # ddev-test-dennis.ddev.site
    upstream ddev-test-dennis.ddev.site-8036 {
    keepalive 100;
                        # ddev-ddev-test-dennis-dba
                        server 172.18.0.5:80;
    }
    # ddev-test-dennis.ddev.site
    upstream ddev-test-dennis.ddev.site-80 {
    keepalive 100;
                        # ddev-ddev-test-dennis-web
                        server 172.18.0.4:80;
    }
    # ddev-test-dennis.ddev.site
    upstream ddev-test-dennis.ddev.site-8025 {
    keepalive 100;
                        # ddev-ddev-test-dennis-web
                        server 172.18.0.4:8025;
    }
```

So the problem is somewhere here (sourced from `containers/ddev-router/nginx.tmpl`). Any clue/ideas?

2020-11-22 00:49 UTC, rfay commented
I think this is https://github.com/jonaseberle/github-action-setup-ddev/issues/5

2020-11-22 17:39 UTC, rfay commented
The fix is in over there, but the bottom line was to `ddev start || (docker cp nginx.tmpl dev-router:/app && ddev start)` with the revised nginx.tmpl.

We can do much better than that, and we can debug the actual source of the reason he had to fork nginx.tmpl, but for now, just trying to get that project going, and it can probably unblock you.

Unfortunately though, every time ddev-router gets stopped, it has to be done over again. 

The immediate fix is to add a ~/.ddev/router-compose.updatenginx.yaml which puts the altered nginx.tmpl in place every time the router starts. Its not hard, needs a build step, I think it should work out OK.

2020-11-22 18:56 UTC, rfay commented
The approach in https://github.com/jonaseberle/github-action-setup-ddev/pull/6/commits/00b9ac617e8ba4177268f8a37c59cd478c37ebe2 should work fine for now and be more sustainable. Just need the nginx.tmpl and the router-compose.nginx_tmpl.yaml copied into ~/.ddev

2020-11-22 20:40 UTC, dennisameling commented
Alright let's see what this does, fingers crossed! 🤞 https://github.com/drud/ddev/pull/2615/commits/92b7945ab7e86f2c21d51248a3b9f4e6cb3ccd28

2020-11-23 11:18 UTC, dennisameling commented
That looks a lot better already! Thanks! Tests that are still failing:

--- FAIL: TestHomeadditions (81.56s)
--- FAIL: TestCreateGlobalDdevDir (79.76s)

@rfay Unfortunately I can't look into things further until the coming weekend; have a packed work week. Please feel free to add/debug things in this PR. In case you want to SSH into the GH Actions VM, you can do so by adding `mxschmitt/action-tmate@v3` to the workflow file. Don't forget to either cancel a job or [continue the workflow](https://github.com/mxschmitt/action-tmate#continue-a-workflow) when you're done, or tmate will keep running until the job times out (6 hours!)

2020-11-23 12:33 UTC, rfay commented
Awesome @dennisameling thanks! 

I used tmate for the other PR, couldn't have done it without it, and when I go back to figure out the actual source of the problem... that will be the only way. Thanks so much for finding that and promoting it. It's always been the best thing about CircleCI, and I don't know how I could live without being able to ssh in and inspect things. 

The two tests you mention are ones that move the global ddev dir IIRC, so that's probably what happens there. 

It may be that I'll solve the underlying problem this week so we don't have to do the workaround with nginx.tmpl, but I'm not certain I'm ready to commit something like that to master so early in the life of v1.16. We'll see. There haven't been many problems, and mostly they're solved by v1.16.1.

2020-11-26 13:32 UTC, rfay commented
I think the best way I'll be able to help with this immediately is to try to completely understand and resolve what's needed with ddev-router, so we don't have to add the nginx.tmpl, as I imagine that's the complexity with those two tests. I hope to be able to work on that in the next few days. It's a holiday weekend here in the US (Thanksgiving) but that may mean I'll get more time for it :)

2020-11-26 16:11 UTC, dennisameling commented
No rush, enjoy Thanksgiving! 😊

2020-11-28 16:43 UTC, rfay commented
I think I have it working without the hack in https://github.com/drud/ddev/pull/2666 - now the only thing I'm wondering is if I should wait to pull that until point releases are done or get it into the next point release. If it gets pulled now onto master, it will be easier to work with sooner. It might introduce just the tiniest bit of risk, and isn't exactly a bugfix for ordinary use.

2020-11-29 00:32 UTC, dennisameling commented
Please do what you think is best for the stability of DDEV at the moment. I'm happy to pause this PR for a while, so you and others can validate the fix properly :blush: thanks for looking into this!!

2020-11-29 13:30 UTC, rfay commented
https://github.com/drud/ddev/pull/2666 is in! So this can be rebased.

That adds a github workflow that can be removed here; I just wanted it to live for a little while because of the tricky changes to ddev-router.

2020-11-29 13:30 UTC, rfay commented
Actually, I'll rebase and remove those right now.

2020-11-29 14:13 UTC, rfay commented
* Rebased
* Removed the upstream github actions that we won't need going forward
* Removed the nginx.tmpl workaround that was added here.

2020-11-29 19:16 UTC, dennisameling commented
CI is green! Thanks a lot @rfay! In the coming days I'll try to finalize at least the bits that are currently in CircleCI 👍🏼

2020-11-30 18:05 UTC, rfay requested changes
Just took a casual pass through to make sure I knew were we were at right now. Overall it seems far more advanced and appropriate than I had any reason to expect. Simple comments added.

2020-11-30 18:05 UTC, rfay commented on .github/workflows/lx-build-and-test.yml
> +          go-version: '^1.15.3'
Can we let this float to latest released?

2020-11-30 18:05 UTC, rfay commented on .github/workflows/macos-setup.sh
> +brew install make mysql mkcert
We may want to lose homebrew on macOS as well, not sure. It's not as slow there, but still it's not as useful as on a real desktop computer.

2020-11-30 18:05 UTC, rfay commented on .travis.yml
> +          time make test DOCKER_ARGS=--no-cache
We don't need --no-cache here I don't think, since these aren't actually used in production right?

2020-11-30 18:05 UTC, rfay commented on Makefile
> +        bash -c "ls /workdir && GOOS=$$GOOS GOARCH=$$GOARCH go build -o $(GOTMP)/bin/$$TARGET -installsuffix static -ldflags \" $(LDFLAGS) \" $(SRC_AND_UNDER)"
Let's not forget to remove the ls unless it's actually useful here.

2020-12-07 11:32 UTC, dennisameling commented
Just a little update that I hope to be working on this tomorrow or on Wednesday. Sorry for the delay, have been super busy with work these weeks!

2020-12-07 12:49 UTC, rfay commented
It's coming along great! Thanks so much for your leadership on this.

2020-12-22 13:20 UTC, dennisameling commented
Just applied some of your suggestions. Making good progress 😊 The macOS hosted runners are incredibly slow to start (20-30 mins), guess GH Actions currently has a large backlog on those.

Are you sure that you want to run the container tests both on Linux and macOS? Sounds like a bit of overkill to me tbh. Saw that you disabled container tests on macOS in Buildkite as well. Would much rather have the "regular" tests running on all three platforms (Linux/macOS/Windows). What do you think?

As for a self-hosted Windows machine(s) - [it's not something GitHub recommends on public repos](https://docs.github.com/en/free-pro-team@latest/actions/hosting-your-own-runners/about-self-hosted-runners#self-hosted-runner-security-with-public-repositories), but I guess the same risk exists for Buildkite. AppVeyor [does have Docker Desktop installed](https://www.appveyor.com/docs/windows-images-software/#docker) with LCOW experimental support, so we might be able to try that? What do you think?

2020-12-22 14:53 UTC, rfay commented
* The container build/test can run only on Linux.
* In Nirvana, all the regular tests (linux/windows/mac) would use the resultant build of the Linux container build if it has changed. I think you already have the container build/test only happening when something changes right? This wouldn't be feasible right now because we'd have to wait multiple hours. But there might be a way to build just the webserver and one or two db servers and then run tests based on them. Not sure. Nirvana is hard to reach.
* I'm way willing to try Appveyor again. I'm probably willing to use self-hosted github as we have pretty clear understanding of what PRs go through, but it's certainly a valid concern. We may have to do self-hosted macOS as well.

2020-12-23 09:22 UTC, dennisameling commented
To speed things up, I'd like to suggest using self-hosted Windows and macOS machines for now. It's just becoming too hacky e.g. with the Virtualbox + VM config in MacOS, which results in a [plethora of issues](https://github.com/drud/ddev/pull/2615/checks?check_run_id=1595252624). Using the _actual_ Docker Desktop on macOS and Windows also much better reflects real-world installations.

- As soon as a new Windows Server LTSC version is released which has WSL2 support ([rumor says](https://www.zdnet.com/article/microsoft-readies-next-version-of-windows-server-ltsc-for-latter-half-of-2021/) that'll be towards the end of 2021), we can switch to that. The technology that AppVeyor is using (LCOW) [is no longer being developed](https://github.com/linuxkit/lcow), so we don't want to be using that I suppose.
- [Docker Desktop Enterprise for Mac](https://github.community/t/is-it-possible-to-install-and-configure-docker-on-macos-runner/16981/12?u=dennisameling) is now available, so let's hope that the GH Actions team will start using it some time next year. Could switch to that then.

Do you have the machines available for this and if yes, would you mind [adding them to the DDEV repo](https://docs.github.com/en/free-pro-team@latest/actions/hosting-your-own-runners/adding-self-hosted-runners)?

2020-12-23 16:19 UTC, rfay commented
Happy to do this, it's just that the transition is a little iffy, since those machines are the buildkite builders :)  
BTW, since we've already been using self-hosted builders forever with buildkite, there's no additional risk. 

I'll be home from vacation in a few days and will try to figure out a transition plan.

2020-12-23 22:28 UTC, dennisameling commented
Happy Holidays! Just did a test with a Windows 10 VM with WSL2 enabled. 

The CI config is very similar to Buildkite's: https://github.com/dennisameling/ddev/compare/switch-to-github-actions...dennisameling:gh-actions-win-temp

CI run (failed due to NFS missing): https://github.com/dennisameling/ddev/runs/1602639248?check_suite_focus=true

Chat later 😊

2020-12-28 16:17 UTC, rfay commented
I expect to be able to work on this this week, and to come up with some test runners. Thanks!

2021-01-01 23:55 UTC, rfay commented
Well, I didn't get there this week, but I did get all the other queued stuff killed off, so next week for sure!

2021-01-02 00:04 UTC, rfay commented
If you could take a look at a rebase, it would be appreciated. I looked a bit, but we had loads of conflicts in the Makefile, as I had to do lots in there to make Dockerfile work on arm64 and mac.  If you have questions about mounting the cache into the container, let's work on that.

2021-01-02 16:25 UTC, dennisameling commented
Rebased 👍🏼 Happy New Year! 🎉

2021-01-04 15:46 UTC, rfay commented
OK, I have 2 macos and 3 windows machines set up as self-hosted builders. 

https://github.com/drud/temp-selfhostedrunner-test shows them working. 

If you want to push forward, go to town! If you're out of time with the new year, I would hope to be able to spend some time with this.

2021-01-05 04:51 UTC, rfay commented
OK, that's it for tonight. This is getting awfully close, congrats on all the great work!

Although I was able to use the macos runners fine on test project, I'm not doing very well with them here. They seem to accept the job and hang at checkout or whatever. Anyway, we'll see what happens when we let this run.

2021-01-05 12:17 UTC, rfay commented
There are a number of things that are not as mature in GitHub Actions as in CircleCI and BuildKite, unfortunately. 

1. CircleCI has easy ssh retries. Github Actions, you have to change the code and push a temp piece of code. 
2. BuildKite and CircleCI have built-in "Cancel redundant builds" features, which avoid using crazy amounts of resources when new commits come into a PR.  This is super important in self-hosted builds, where we have limited resources. There are a number of Actions that deal with this in basically the same way; the leader seems to be https://github.com/marketplace/actions/cancel-workflow-action. Unfortunately, I don't think we can use that because it exposes an important secret to forked builds.  And I don't think we can do self-hosted without this feature. 

So I'm wondering if we can't do macOS and Windows with GitHub Actions.

2021-01-05 13:43 UTC, rfay commented
I'm afraid GitHub Actions is in no way ready for self-hosted runners.

* There's no way to find out what the runner is working on, or to solve the question of "Why is this runner active, what's it doing?"
* The scripts provided for starting/stopping runner services don't even have comments suggesting what their arguments are.
* Cancelling a workflow doesn't necessarily work; you can click the button over and over.

Buildkite is vastly better for the self-hosted build 😦 

I uninstalled and reinstalled the two macOS runners that were stuck running something (and had an infinite backlog, who knows what), in case you want to experiment a bit. Feel free to experiment in the simpler https://github.com/drud/temp-selfhostedrunner-test as well. I invited you to that repo with full privileges.  If you'd like, I can also give you login access to the two macs.

2021-01-07 04:37 UTC, rfay commented
* I winnowed this down to just the linux tests, and distributed them a bit. I'm happy with the full matrix of tests finishing in about an hour. And of course this saves quite a lot of what we spend on CircleCI
* I tested out the cancel workflow technique, with a new push cancelling running workflows, but it doesn't work because of the fork-pr technique.
* It's not possible at all to pass real secrets to forked workflows, although we may be able to pass minimal secrets via environment variables (limited privilege pantheon, limited privilege ddev-live, dockerhub token). I'm not sure that's even possible via configured environment variables though. They can obviously be added to the workflow files but I'm not willing to go that far. 
* I think this may be a usable or near-usable setup. Sadly no mac or windows at all. There are just a few changes that were made to container builds and such that I need to understand before pulling. I'll try to mark them as a review, but it would be lovely if we could do a zoom or something and spend a half hour or so going through the differences.

2021-01-08 22:13 UTC, dennisameling commented
Thanks for your work on this - I'll check back here some time next week. Have to get some other things done over the weekend 😊 keep in touch!

2021-01-08 22:15 UTC, rfay approved these changes
This is ready to go. Thanks for the amazing effort. There will be little followups. I don't know what happens to the artifacts from the build at this point, so we'll go find them. 

There are a few things that can't really be done on github actions for a forked PR workflow:

* Cancelling a redundant build (which would be necessary to use the self-hosted runners)
* Testing anything that needs a secret
    * Pantheon
    * ddev-live
    * Authenticated docker pulls

But we can just keep those things on CircleCI for now. Maybe GitHub Actions will mature and provide a way to do some of these things, even though they have security issues. 

Anyway, I think this is good to go as soon as it's green.

2021-01-09 04:16 UTC, merged

2021-01-09 04:19 UTC, rfay commented
Congratulations and thanks @dennisameling !

2021-01-09 13:54 UTC, dennisameling commented
This is exciting! Thanks for pushing this over the finish line! Definitely needs some optimizations here and there, but this is a great start 🚀