Bump NSIS to 3.06.1
drud/ddev pull request #2659
Opened 2020-11-24 13:40 UTC by gilbertsoft

## The Problem/Issue/Bug:

## How this PR Solves The Problem:

## Manual Testing Instructions:

## Automated Testing Overview:

## Related Issue Link(s):

## Release/Deployment notes:

2020-11-24 14:30 UTC, rfay commented
I'll certainly manually test this before pulling, but are there any specific testing techniques?

2020-11-28 08:33 UTC, gilbertsoft commented
We only have to do a quick test if the path manipulation still works correctly, I see the following cases:

- fresh install, DDEV install folder is not set in $PATH
- update, DDEV install folder extists once in $PATH
- update with multiple DDEV install folders in $PATH (fix for the wrong installer which added the path again on updates)
- removal of the folder on uninstall

2020-11-28 08:48 UTC, gilbertsoft commented
I've checked the steps above and it works fine like expected. Releasing now a new EnVar plugin...

2020-11-28 08:55 UTC, gilbertsoft commented
Release is done and will be used for all new installer builds here. As said this patch will only update the assets on Linux to latest NSIS.

2020-11-28 12:57 UTC, rfay commented
Thanks so much. Is there any urgency to this? Does it need to go into v1.16 point relesaes? (I expect at least one more point release)

2020-11-28 16:35 UTC, gilbertsoft commented
No, not urgent. This will only ensure the Windows installer built on Linux uses the same assets like the one on MacOS does. But anyway it wont hurt anything as this part is not used for the production builds. It's just a cosmetic change.

Because we always use the latest stable release of the EnVar plugin the new release will of course be included with the next release.

2020-12-28 16:24 UTC, rfay requested changes
It turns out that makensis is also installed (with 3.06.1) via homebrew. We should either remove that or use this one, I'm not sure which is appropriate. I see that line 48 puts it in /usr/local/share, but the homebrew install puts it in ~linuxbrew.

2021-03-03 18:27 UTC, merged