Updates local docs theme to match live
drud/ddev pull request #2840
Opened 2021-02-26 14:55 UTC by unn

2021-03-01 14:35 UTC, rfay commented
@unn thanks for this work! 

You'll note that the tests in the build fail, it's tested like this: https://github.com/drud/ddev/blob/dc26ba17b1c6a934ded420cae94bebf641e82033/.github/workflows/docscheck.yml#L30-L34

Please update what you think should be updated to make that work correctly.

2021-03-01 17:33 UTC, unn commented
Thanks @rfay! On my list.

2021-03-01 18:33 UTC, rfay requested changes
The requirements.txt and related things seem like a great step forward. Could we put them in a .mkdocs directory or something so they have context? Maybe put everything mkdocs related into .mkdocs?

2021-03-04 15:14 UTC, rfay approved these changes
Looking good, I'll poke around your forked docs and this should go in. Thanks so much!

2021-03-04 15:14 UTC, rfay commented on requirements.txt
> +Babel==2.8.0
```suggestion
# This requirements.txt file is exclusively for mkdocs docfile creation, and doesn't have anything
# specifically to do with ddev.
Babel==2.8.0
```

2021-03-04 15:17 UTC, rfay commented
I *love* the table of contents on the right side. Since it's context-sensitive it was a little hard to figure out what it was contents *for* at first, but it's a great step forward. 
<img width="1339" alt="Using_the_CLI_-_DDEV-Local_Documentation" src="https://user-images.githubusercontent.com/112444/109985448-fd970f80-7cc1-11eb-9e5f-b685f67b5489.png">

2021-03-04 17:59 UTC, merged

2021-03-04 17:59 UTC, rfay commented
Yay, thanks and congratulations @unn !

2021-03-04 18:00 UTC, rfay commented
Makes me want to do a prerelease just to make this show up.