Prepare make (with docker-up) during prebuild
drud/ddev pull request #2844
Opened 2021-03-01 14:42 UTC by shaal

## The Problem/Issue/Bug:
Users have to wait for make to run when starting a workspace.

## How this PR Solves The Problem:
Make (with docker-up) can run during prebuild.
A user can start workspace after make already finished running, and ready to work with `ddev`.

## Manual Testing Instructions:
Run Gitpod in this PR, and confirm you can run `ddev` in the terminal.

## Automated Testing Overview:

## Related Issue Link(s):

## Release/Deployment notes:

2021-03-01 14:45 UTC, rfay approved these changes
Love it!

2021-03-01 14:45 UTC, rfay commented on .gitpod.yml
> +      make
This is awesome. Gets the golang-build-container pulled in advance! Hopefully there aren't permissions problems in there.

2021-03-01 14:47 UTC, rfay commented
I see this in the terminal once it comes up:

```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
Linked pre-push.allchecks as pre-push git hook
```

Looks like you needed to redirect your `docker ps` - `docker ps 2>/dev/null`

2021-03-01 14:50 UTC, rfay requested changes
Unfortunately, I don't think this can work until the gitpod permissions bug is fixed.

```
gitpod /workspace/ddev $ make 
building .gotmp/bin/linux_amd64/ddev from ./cmd/... ./pkg/...
go: creating work dir: mkdir /tmp/go-build1509598969: permission denied
make: *** [Makefile:115: .gotmp/bin/linux_amd64/ddev] Error 1```

2021-03-01 15:09 UTC, shaal commented
@rfay Thanks for looking into it.
We'll have to wait until the Gitpod bug is fixed - https://github.com/gitpod-io/gitpod/issues/3174

2021-03-01 15:11 UTC, rfay commented
It also means (I think) that we'll need the `docker rmi` or docker pull to even make restored workspaces work.

2021-03-01 15:23 UTC, shaal commented
True! We forgot to test restarting the workspace

2021-03-02 21:49 UTC, rfay commented
I'd like to close this for now and reopen it when it becomes actionable. So many things are not practical until they fix that bug as well as https://github.com/gitpod-io/gitpod/issues/2459 (so we can build docker images).

2021-03-02 21:49 UTC, closed without merging