Comment out dangerous commands, and move terminus alias
drud/ddev pull request #2963
Opened 2021-04-24 16:31 UTC by amitaibu

## The Problem/Issue/Bug:

Comment out dangerous commands in Pantheon integration.

## Related Issue Link(s):

https://github.com/drud/ddev/pull/2957#issuecomment-826106788

2021-04-24 16:31 UTC, amitaibu commented on cmd/ddev/cmd/dotddev_assets/providers/pantheon.yaml.example
> +#    terminus aliases 2>/dev/null
`terminus aliases` moved here

2021-04-24 18:02 UTC, rfay requested changes
* This approach will break the push tests, so we probably need to do something like adding an environment variable like "DDEV_ALLOW_PUSH=true" instead of the commenting-out technique you've done.
* We need to do it with all the example providers, not just this one.

2021-06-03 20:01 UTC, rfay commented
This one is superceded by #2966 right @amitaibu ? Did you get everything you wanted in there and we should close this one?

2021-06-04 12:44 UTC, amitaibu commented
Yes, this one can be closed. To be honest, I never got back to https://github.com/drud/ddev/pull/2966 , sorry :smiley_cat:

2021-06-04 12:44 UTC, closed without merging

2021-06-04 12:50 UTC, rfay commented
#2966 has excellent potential. One of us will get back to it :)