Run mysql under its own user if Docker is run as root
drud/ddev pull request #3026
Opened 2021-05-29 02:23 UTC by hussainweb

## The Problem/Issue/Bug:

The problem is detailed in #3025.

## How this PR Solves The Problem:

It solves it according to the solution described in the above issue. This is the same way the official images do this as well.

## Manual Testing Instructions:
WIP

## Automated Testing Overview:
WIP

## Related Issue Link(s):
#3025 

## Release/Deployment notes:
This shouldn't affect any other workflows. New database docker images would be needed as part of the release.

2021-05-29 02:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/drud/ddev?pullRequest=3026) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/drud/ddev?pullRequest=3026) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/drud/ddev?pullRequest=3026) it.</sub>

2021-05-30 22:34 UTC, rfay requested changes
I don't expect that this will work, because the container will run as the mysql user I guess, which is 999 in this container. But the /var/lib/mysql will already have been initialized with another uid, right? 

I think it might be better to allow mysql to run as root (if that works for both mysql and mariadb). 

You'll need to actually manually test this by building it (`make VERSION=<your_tag>` in containers/ddev-dbserver), and you'll need to have a specific manual test plan.

There are some hints about how to build and use a PR that has a particular container at https://github.com/drud/ddev/blob/master/docs/developers/building-contributing.md

Please try that out manually and see how you do. 

Again, it sounds to me like this might not be the most obvious answer to the problem you're trying to solve.

2021-05-31 19:02 UTC, hussainweb commented
Thanks, @rfay for reviewing this. I am considering your message and will build and test this manually. But for the sake of clarity, I will try to restate the problem here.

I want to be able to run this image directly similar to how we can already run other images from MySQL and MariaDB. Consider these hypothetical examples. Also, you can see the same message about switching to the `mysql` user in logs for both official images. Logs below.

Again, thanks for reviewing this and I will get back to you with the results from my testing.

---

MySQL 8.0 with emulation (as I have M1)
`docker run --platform linux/amd64 -e MYSQL_ALLOW_EMPTY_PASSWORD=true mysql:8.0`

<details><summary>Full log</summary>
<p>

```
2021-05-31 18:50:17+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.25-1debian10 started.
2021-05-31 18:50:17+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2021-05-31 18:50:17+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.25-1debian10 started.
2021-05-31 18:50:18+00:00 [Note] [Entrypoint]: Initializing database files
2021-05-31T18:50:18.361203Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.25) initializing of server in progress as process 100
2021-05-31T18:50:18.435033Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2021-05-31T18:50:18.454483Z 1 [ERROR] [MY-012585] [InnoDB] Linux Native AIO interface is not supported on this platform. Please check your OS documentation and install appropriate binary of InnoDB.
2021-05-31T18:50:18.455114Z 1 [Warning] [MY-012654] [InnoDB] Linux Native AIO disabled.
2021-05-31T18:50:19.200329Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2021-05-31T18:50:22.905901Z 6 [Warning] [MY-010453] [Server] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
2021-05-31 18:50:28+00:00 [Note] [Entrypoint]: Database files initialized
2021-05-31 18:50:28+00:00 [Note] [Entrypoint]: Starting temporary server
2021-05-31T18:50:29.156527Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.25) starting as process 151
2021-05-31T18:50:29.303277Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2021-05-31T18:50:29.337274Z 1 [ERROR] [MY-012585] [InnoDB] Linux Native AIO interface is not supported on this platform. Please check your OS documentation and install appropriate binary of InnoDB.
2021-05-31T18:50:29.338086Z 1 [Warning] [MY-012654] [InnoDB] Linux Native AIO disabled.
2021-05-31T18:50:29.722859Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2021-05-31T18:50:30.269302Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: /var/run/mysqld/mysqlx.sock
2021-05-31T18:50:30.828073Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
2021-05-31T18:50:30.829604Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
2021-05-31T18:50:30.836418Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
2021-05-31T18:50:30.961600Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.25'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server - GPL.
2021-05-31 18:50:31+00:00 [Note] [Entrypoint]: Temporary server started.
Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.

2021-05-31 18:50:40+00:00 [Note] [Entrypoint]: Stopping temporary server
2021-05-31T18:50:40.723314Z 10 [System] [MY-013172] [Server] Received SHUTDOWN from user root. Shutting down mysqld (Version: 8.0.25).
2021-05-31T18:50:42.325430Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.25)  MySQL Community Server - GPL.
2021-05-31 18:50:42+00:00 [Note] [Entrypoint]: Temporary server stopped

2021-05-31 18:50:42+00:00 [Note] [Entrypoint]: MySQL init process done. Ready for start up.

2021-05-31T18:50:43.628774Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.25) starting as process 1
2021-05-31T18:50:43.736098Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2021-05-31T18:50:43.767719Z 1 [ERROR] [MY-012585] [InnoDB] Linux Native AIO interface is not supported on this platform. Please check your OS documentation and install appropriate binary of InnoDB.
2021-05-31T18:50:43.768442Z 1 [Warning] [MY-012654] [InnoDB] Linux Native AIO disabled.
2021-05-31T18:50:44.101011Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2021-05-31T18:50:44.719014Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
2021-05-31T18:50:44.984187Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
2021-05-31T18:50:44.985481Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
2021-05-31T18:50:44.995513Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
2021-05-31T18:50:45.104918Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.25'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
2021-05-31T18:50:54.730472Z 0 [System] [MY-013172] [Server] Received SHUTDOWN from user <via user signal>. Shutting down mysqld (Version: 8.0.25).
2021-05-31T18:50:55.826303Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.25)  MySQL Community Server - GPL.
```

</p>
</details>

---

MariaDB 10.5
`docker run -e MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true mariadb:10.5`

<details><summary>Full log</summary>
<p>

```
2021-05-31 18:52:33+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.5.10+maria~focal started.
2021-05-31 18:52:33+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2021-05-31 18:52:33+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.5.10+maria~focal started.
2021-05-31 18:52:33+00:00 [Note] [Entrypoint]: Initializing database files


PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
To do so, start the server, then issue the following command:

'/usr/bin/mysql_secure_installation'

which will also give you the option of removing the test
databases and anonymous user created by default.  This is
strongly recommended for production servers.

See the MariaDB Knowledgebase at https://mariadb.com/kb or the
MySQL manual for more instructions.

Please report any problems at https://mariadb.org/jira

The latest information about MariaDB is available at https://mariadb.org/.
You can find additional information about the MySQL part at:
https://dev.mysql.com
Consider joining MariaDB's strong and vibrant community:
https://mariadb.org/get-involved/

2021-05-31 18:52:33+00:00 [Note] [Entrypoint]: Database files initialized
2021-05-31 18:52:33+00:00 [Note] [Entrypoint]: Starting temporary server
2021-05-31 18:52:33+00:00 [Note] [Entrypoint]: Waiting for server startup
2021-05-31 18:52:33 0 [Note] mysqld (mysqld 10.5.10-MariaDB-1:10.5.10+maria~focal) starting as process 103 ...
2021-05-31 18:52:33 0 [Note] InnoDB: Uses event mutexes
2021-05-31 18:52:33 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2021-05-31 18:52:33 0 [Note] InnoDB: Number of pools: 1
2021-05-31 18:52:33 0 [Note] InnoDB: Using ARMv8 crc32 + pmull instructions
2021-05-31 18:52:33 0 [Note] mysqld: O_TMPFILE is not supported on  [...]

2021-06-15 20:10 UTC, rfay commented
Since you haven't been back to this to manually test or anything, I'm going to close this for now. Happy to reopen when you're ready to work with it some more and go through manual building and testing. As always, happy to continue the conversation here or elsewhere.

2021-06-15 20:10 UTC, closed without merging

2021-06-15 20:12 UTC, hussainweb commented
I understand. I have been involved with a few other things and will reopen this once I get a chance to move ahead here. Thanks.