Document how to restore DDEV management to a file
drud/ddev pull request #3213
Opened 2021-09-03 13:27 UTC by mlncn

## The Problem/Issue/Bug:

## How this PR Solves The Problem:

## Manual Testing Instructions:

## Automated Testing Overview:

## Related Issue Link(s):

## Release/Deployment notes:

2021-09-03 13:56 UTC, rfay requested changes
Thanks so much for this!

Actually, the best way to work around this is just to delete the file in question and do a `ddev start` and ddev will recreate it. That will make this section much simpler. Feel free to push another commit with that suggestion. However, this isn't CMS-specific. It probably belongs in another file in the same directory, call it hints_and_tips.md and add it to mkdocs.yml.

2021-09-04 15:24 UTC, rfay commented
On second thought, can we just add this to https://ddev.readthedocs.io/en/latest/users/topics/settings_files/ ?

2021-09-04 16:32 UTC, mlncn commented
Sure!  I don't think i found that page :sob:, but as long as the warning messages are added there people will find it!

2021-09-09 02:04 UTC, rfay commented
I added this in https://github.com/drud/ddev/commit/9cc8fe4c5f2a540061d117901013ceade2af3d87 - please see if you like it and it solves the problem you were raising. Thanks @mlncn !

2021-09-09 02:04 UTC, closed without merging