Update special-environments.md
drud/ddev pull request #3482
Opened 2021-12-28 22:10 UTC by funkvn

MariaDB 10.1 is now out of support, so DDEV runs only with 10.2 or higher.

2021-12-28 22:23 UTC, rfay requested changes
The images are still there, see https://hub.docker.com/_/mariadb?tab=tags&page=1&name=10.1 - I doubt they'll remove them. 

It would take more than just the doc to remove the 10.1 option for arm64.

Are you having trouble with arm64 MariaDB 10.1?

2021-12-28 22:44 UTC, funkvn commented
> It would take more than just the doc to remove the 10.1 option for arm64.

well, but...

> Are you having trouble with arm64 MariaDB 10.1?

yes. It does not work with 10.1 and 10.2 works fine.
If there is no 10.1 anymore on https://mariadb.org/ (header) or https://mariadb.org/download/ – don't know about the details of removing 10.1 from the official support.

I got this error while `ddev start`:
```
#12 0.187 standard_init_linux.go:228: exec user process caused: exec format error
#12 ERROR: executor failed running [/bin/bash -c (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username" || useradd  -l -m -s "/bin/bash" --gid "$gid" --comment '' "$username")]: exit code: 1
```

A `docker run` failed as well:
```
$ docker run ab420cdc23d0                         
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
standard_init_linux.go:228: exec user process caused: exec format error
```

Switching to 10.2 (or 10.3/later) fixes that problem. 

Greetings
  Valentin

2021-12-28 23:28 UTC, rfay commented
Thanks for pointing out this problem. It was actually an error in the build process, fixed in 

* #3483 

I pushed the missing arm64 image for mariadb 10.1

Please `ddev poweroff` and try again with mariadb 10.1

2021-12-29 23:36 UTC, rfay commented
Looking forward to hearing from you if that sorted it out, but closing this for now. Feel free to comment here and let me know.

2021-12-29 23:36 UTC, closed without merging

2022-01-03 09:00 UTC, funkvn commented
Thanks Randy! Now it works with MariaDB 10.1 fine.

I misunderstood the documentation in that way, that only supported versions of MariaDB are available, because only for those the images were created (by the vendor). Blame it on the non-native speaker. Sorry for the trouble.

2022-01-03 14:04 UTC, rfay commented
No, you didn't really misunderstand. Mostly the docs weren't completely correct.  Actually, it looks like we could now do 10.0 as well, but there hasn't really been any call for that. 

Again, thanks for catching this. Old versions of TYPO3 actually need 10.1, but that's the only old-db use I know of. 

Was there a particular reason you needed 10.1 @funkvn ?