#3549 Prevent unconditional overriding config sync directory
drud/ddev pull request #3550
Opened 2022-01-26 13:45 UTC by leymannx

## The Problem/Issue/Bug:

#3549

## How this PR Solves The Problem:

Check if `$settings['config_sync_directory']` is empty before setting it.

## Manual Testing Instructions:

1. Have a Drupal 9 project. Define a config sync directory in the default `settings.php` file, e.g. `$settings['config_sync_directory'] = $app_root . '/../config/sync';`.
2. Export config.
3. Config should be exported to `config/sync` directory outside the webroot instead of `sites/default/files/sync`.

## Automated Testing Overview:

## Related Issue Link(s):

#3549 

## Release/Deployment notes:

2022-01-26 13:50 UTC, rfay commented
Awesome. You can manually test this if you want, see https://github.com/drud/ddev/blob/master/docs/developers/building-contributing.md#testing-a-pr

2022-01-26 14:30 UTC, leymannx commented
@rfay – Okay, yeah, I'll try the manual testing later today.

2022-01-26 20:47 UTC, leymannx commented
@rfay – Wow, magic! I did the manual testing with the binary artifact (ddev-macos-amd64.zip) and the missing if-request was there now and behaved as wished. All `ddev drush -y cex` and `ddev drush -y cim` now picking up the config from the correct directory again. 🙂

2022-01-26 21:22 UTC, rfay commented
Awesome, thanks so much!

2022-01-27 02:01 UTC, rfay requested changes
I know that Drupal 8 is obsolete, but shouldn't this be fixed in drupal8/settings.ddev.php as well?

2022-01-27 06:46 UTC, leymannx commented
Drupal 8 still has the condition around the setting:

https://github.com/drud/ddev/blob/e54753a09c9f3f68c49383fe00a03805cdee4f75/pkg/ddevapp/drupal/drupal8/settings.ddev.php#L43-L55

2022-01-27 13:55 UTC, rfay approved these changes
Tested, works great, thannks!

2022-01-27 13:55 UTC, merged