WIP: Remove warning about missing SegmentKey in json mode
drud/ddev pull request #3574
Opened 2022-02-05 17:14 UTC by nico-loeber

## The Problem/Issue/Bug:
The warning about the missing SegmentKey generates a second obejct on output which causes it to be invalid for parsers.

## How this PR Solves The Problem:
In json output mode the warning is no longer triggert.

## Manual Testing Instructions:
Execute ddev describe -j on a self build ddev binary. The following warning must not appear:
```json
{
  "level": "warning",
  "msg": "Instrumentation is opted in, but SegmentKey is not available.",
  "time": "2022-02-05T16:52:26+01:00"
}
```

## Automated Testing Overview:
N/A

## Related Issue Link(s):
N/A

## Release/Deployment notes:
N/A

2022-02-05 17:26 UTC, rfay approved these changes
This looks perfect. Please just manually check to see that the warning shows in non-json mode still. Thanks!

2022-02-05 19:03 UTC, nico-loeber commented
The warning is still shown in the human readable output of the commands:

![image](https://user-images.githubusercontent.com/18308418/152655164-24a67d1f-6739-4182-97bf-d15fd170a005.png)

Can be tested in gitpod

- run ddev poweroff
- edit .ddev/config.yml
- set `instrumentation_opt_in: true`
- run ddev start
- run ddev describe
- run dddev describe --json-output

2022-02-05 19:07 UTC, rfay commented
Awesome. Let me know when you're happy with it and I'll pull (after tests run)

2022-02-06 11:57 UTC, nico-loeber commented
> Awesome. Let me know when you're happy with it and I'll pull (after tests run)

Ready when you are

2022-02-07 15:52 UTC, rfay commented
The weird thing here is that output.UserOut.Warning() should already have been outputting json and not breaking the json output. Maybe it's not properly initialized at this point.

2022-02-07 18:28 UTC, rfay requested changes
Hmm, I'd love to figure out how to solve the json format problem, but I guess we'll be OK with the current approach.

The one thing we can surely do though is to make this message less concerning to people who are testing PR builds or local builds. What do you think about the suggested terminology here?

2022-02-07 18:28 UTC, rfay commented on cmd/ddev/cmd/root.go
>  		output.UserOut.Warning("Instrumentation is opted in, but SegmentKey is not available.")
```suggestion
		output.UserOut.Warning("Instrumentation is opted in, but SegmentKey is not available. This usually means you have a locally-built ddev binary or one from a PR build. It's not an error. Please report it if you're using an official release build.")
```

2022-02-07 18:37 UTC, rfay commented
I'm sure you already know that your code can set DDEV_NO_INSTRUMENTATION=true before interacting with ddev and also solve all this.

2022-02-08 04:43 UTC, merged