#3518: Supress feedback on command failure
drud/ddev pull request #3627
Opened 2022-02-24 22:17 UTC by bserem

## The Problem/Issue/Bug:
#3518 

## How this PR Solves The Problem:
It does not print a message when a command fails, thus only display the original command response and not the one from ddev/docker

| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/520237/155616662-33a8d8ab-2165-4164-a887-ffd6d57d16d4.png) | ![image](https://user-images.githubusercontent.com/520237/155616081-38509a31-1a97-4eb4-9097-f095b20a64b7.png) |

## Manual Testing Instructions:
Do `ddev exec "ls whatever"` with and without the changes

## Related Issue Link(s):
#3518 

## Release/Deployment notes:
Unaware if it affects things elsewhere.

2022-02-24 22:49 UTC, rfay requested changes
I don't think we ever discussed just *not* outputting the failure. We talked about a config element that would allow it to be suppressed. This will work for you but nobody else. I imagine you're planning to work toward that config element.

2022-02-24 22:56 UTC, bserem commented
I can give it a try when time allows it, but Go is not my cup of tea, so it will take some time

2022-02-27 20:51 UTC, bserem commented
Let's see if I got that right:

1. Normal command (unaffected by PR)
2. JSON Output (unaffected by PR)
3. **New** global command flag, `--no-output`, supressing output to StdErr
4. **Updated** Help message, with the new flag

![image](https://user-images.githubusercontent.com/520237/155899311-e6d7ce5f-e0b9-4ba8-aed9-5d04128344f5.png)

2022-02-27 20:55 UTC, rfay reviewed
If no-output is set... this will affect everything, right? I think your goal was just to affect `ddev exec`, right? This will affect hooks, output from loads of other things...

2022-02-27 21:31 UTC, bserem commented
Right... Well then, I honestly don't know if I can do it. I can move the flag under `exec`, but then it does not output an error, so no `exit` code is sent to bash, so a sequence of commands triggered by exec will run to the end (example: a failing `pre-commit` will continute to `commit-msg`).

2022-02-27 21:39 UTC, rfay commented
Are you committed to doing this with `ddev exec`? There are so many ways to do these things. You can `ddev ssh` as you already know. You can `ddev exec` a bash script that manages the output. There are so many different things you can do. 

In this case, I expected that you would change `ddev exec` to redirect the stderr output, or something like that. 

But still, it seems to me like you're killing the messenger instead of finding a way to manage the problem.

2022-03-03 17:42 UTC, gilbertsoft commented
I'm not sure if this a good option. To surpress warnings to upstream simply do something like this:

```
ddev exec 'ls randomdir || true'
```

Why should we surpress a real failure? Does not make much sense to me.

2022-03-03 20:14 UTC, bserem commented
@gilbertsoft I was not aware of `|| true`, and it seems none of us was (see #3518). I'll give it a go soon(ish).

The idea was not to supress the failure, only to hide the docker/ddev message, since it is a duplicate. I have added a lot of screenshots in the issue to make this as clear as possible.

This task apparently was more complex than I initially anticipated and like both you and Randy said I am very far from an ideal solution.
I am taking notes on all the suggestions and try them when I can, but I am starting to believe it doesn't make much sense. Maybe I should pause on this after all.

Thanks

2022-03-04 12:19 UTC, gilbertsoft commented
The ` || true` is a common bash workaround to surpress errors. Wondering nobody had suggested it before. I'm often using it for composer scripts and also in bash scripts where an error may happen but should not block the further execution.

I also had a look at your issue yesterday and for me it looks like you should fix the input which seems to be wrong and that's why you get a warning.

2022-03-19 19:00 UTC, rfay commented
This has been idle for 3 weeks, so I'm going to close it for now, happy to continue the conversation here or elsewhere, and we can reopen if you want to push more into it.

2022-03-19 19:00 UTC, closed without merging