Install GraphicsMagick by default, fixes #3569
drud/ddev pull request #3629
Opened 2022-02-25 09:22 UTC by gilbertsoft

## The Problem/Issue/Bug:

GraphicsMagick is often used with TYPO3 instead of ImageMagick.

## How this PR Solves The Problem:

This patch adds the graphicsmagick package to the ddev-php-base image.

## Related Issue Link(s):

#3569

## Release/Deployment notes:

This change has no impact.

2022-02-25 09:43 UTC, jonaseberle approved these changes

2022-02-26 02:02 UTC, rfay requested changes
This will need a little more work. I built it (`make VERSION=test` in the containers/ddev-php-base directory). Run it then with `docker run -it --rm drud/ddev-php-base:test`

* The php extension is not enabled... I expect it's needed right? This currently just installs the utility.  The `gmagick` extension needs to be installed. 
* The php default configs (/etc/php/<version>/conf.d)  are not installed, but that may not be necessary. 

You can see the setup for loading the PHP extension packages at https://github.com/drud/ddev/blob/cd2edafc5f6821ea11acb32891c3e96bb7aeb55e/containers/ddev-php-base/Dockerfile#L85-L98

2022-02-26 09:48 UTC, gilbertsoft commented
>     * The php extension is not enabled... I expect it's needed right? This currently just installs the utility.  The `gmagick` extension needs to be installed.

As already said by Jonas, for TYPO3 we only need the binaries and no extension.

Are there other requests to install GM by default where the PHP extension is needed? If yes, I'd add it.

2022-02-26 13:35 UTC, gilbertsoft commented
Also added the extension now. According to https://www.php.net/manual/en/gmagick.configuration.php no configuration is needed.

2022-02-26 14:32 UTC, rfay commented
Thanks!

2022-02-27 00:00 UTC, rfay commented
I guess php*imagick and php*gmagick are mutually exclusive:
```
# apt-get install php5.6-gmagick
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  gsfonts libgraphicsmagick-q16-3 libwmf0.2-7
Suggested packages:
  graphicsmagick-dbg libwmf0.2-7-gtk
Recommended packages:
  ttf-dejavu-core
The following packages will be REMOVED:
  php5.6-imagick php7.0-imagick php7.1-imagick php7.2-imagick php7.3-imagick php7.4-imagick php8.0-imagick php8.1-imagick
The following NEW packages will be installed:
  gsfonts libgraphicsmagick-q16-3 libwmf0.2-7 php5.6-gmagick
0 upgraded, 4 newly installed, 8 to remove and 39 not upgraded.
Need to get 4350 kB of archives.
After this operation, 4508 kB of additional disk space will be used.
Do you want to continue? [Y/n]
```

2022-02-27 01:35 UTC, rfay approved these changes
I reverted the add of the php extension since it's incompatible with imagick, rebased, and pushed the relevant images.

Please test this and see if it does what you want, @gilbertsoft @jonaseberle - You can easily test on Gitpod with the gitpod link, or download the built artifacts from https://github.com/drud/ddev/actions/runs/1904743275

2022-02-27 11:19 UTC, jonaseberle approved these changes

2022-02-27 12:56 UTC, gilbertsoft commented
> I guess php_imagick and php_gmagick are mutually exclusive:

Another reason not using the extension.

Works like expected for TYPO3.

2022-02-28 04:04 UTC, merged

2024-06-18 11:48 UTC, rfay commented
It's hard to understand your question @sal-lochbaum  - On TYPO3 the additional.php does configure Graphicsmagick by default. And DDEV does have the package installed in ddev-webserver. 

And of course you can override the additional.php or turn off settings management. 

Full details about settings management at https://ddev.readthedocs.io/en/stable/users/usage/cms-settings/

Please open a new issue with a specific question, or join us in [discord](https://discord.gg/5wjP76mBJD) for a discussion.