Allow quoting of `ddev magento` command name and arguments
drud/ddev pull request #3745
Opened 2022-04-01 10:17 UTC by INblau-LucaGerhardt

#3743 `--help` flag not working within Magento 2 commands

## The Problem/Issue/Bug:
`bin/magento` commands via `ddev magento` not working with `--help` flag
## How this PR Solves The Problem:
The changes allow for the Magento 2 command name and argument to be wrapped in double quotes, allowing to pass the `--help` flag within.
## Manual Testing Instructions:
Run `ddev magento "setup:upgrade --help"`, expected output would be something like
```
Description:
  Upgrades the Magento application, DB data, and schema

Usage:
  setup:upgrade [options]

Options:
      --keep-generated                             Prevents generated files from being deleted.        
                                                   We discourage using this option except when deployin
g to production.
                                                   Consult your system integrator or administrator for 
more information.
      --convert-old-scripts[=CONVERT-OLD-SCRIPTS]  Allows to convert old scripts (InstallSchema, Upgrad
eSchema) to db_schema.xml format [default: false]
      --safe-mode[=SAFE-MODE]                      Safe installation of Magento with dumps on destructi
ve operations, like column removal
      --data-restore[=DATA-RESTORE]                Restore removed data from dumps
      --dry-run[=DRY-RUN]                          Magento Installation will be run in dry-run mode [de
fault: false]
      --magento-init-params=MAGENTO-INIT-PARAMS    Add to any command to customize Magento initializati
on parameters
                                                   For example: "MAGE_MODE=developer&MAGE_DIRS[base][pa
th]=/var/www/example.com&MAGE_DIRS[cache][path]=/var/tmp/cache"
  -h, --help                                       Display this help message
  -q, --quiet                                      Do not output any message
  -V, --version                                    Display this application version
      --ansi                                       Force ANSI output
      --no-ansi                                    Disable ANSI output
  -n, --no-interaction                             Do not ask any interactive question
  -v|vv|vvv, --verbose                             Increase the verbosity of messages: 1 for normal out
put, 2 for more verbose output and 3 for debug
```
## Automated Testing Overview:

The PR slightly changes existing behaviour, no new tests are needed.
## Related Issue Link(s):
#3743 
## Release/Deployment notes:

None

2022-04-01 19:18 UTC, rfay commented
Failures are due to composer having changed the output of `composer --version`, not your fault :)

2022-04-08 08:40 UTC, rfay commented
Rwbased

2022-05-11 22:29 UTC, rfay requested changes
It seems to me that if we're doing this for magento it would only make sense to do it for all the items in global_dotddev_assets/commands/web - the need and result are the same aren't they? Would you be willing to take this on and do some testing to make sure it's appropriate?

2022-06-01 07:12 UTC, INblau-LucaGerhardt commented
Hi @rfay,
I had a feeling, that this might change the shell script behaviour too much. Depending on the usage of different cli tools within ddev, workarounds like [this](https://github.com/drud/ddev/issues/3743#issuecomment-1092731512) (from original issue) might do the trick without touching ddev?

2022-06-01 14:03 UTC, rfay commented
As suggested in https://github.com/drud/ddev/issues/3743#issuecomment-1094670673 is `ddev magento help setup:upgrade` good enough for your situation?

2022-06-02 08:18 UTC, INblau-LucaGerhardt commented
It is certainly enough for my situation.

2022-06-02 22:11 UTC, rfay commented
If it's good enough I'm going to go ahead and close this, thanks!

2022-06-02 22:11 UTC, closed without merging