Snapshot only running apps (#3707)
drud/ddev pull request #3749
Opened 2022-04-02 19:33 UTC by mikebarkas

## The Problem/Issue/Bug:
`ddev snapshot --help` command says ddev snapshot --all should only snapshot running projects.
It still tries to snapshot a stopped project and then fails.

## How this PR Solves The Problem:
`ddev snapshot --all` ignores stopped projects
Checks `app.SiteStatus()` before `createAppSnapshot(app)`

## Manual Testing Instructions:

- Have two or more projects
- Stop one project and start the others
- Execute ddev snapshot --all
- Only running apps will have snapshots created

## Automated Testing Overview:

Run existing tests

## Related Issue Link(s):
#3707

## Release/Deployment notes:

No deployment changes

2022-04-02 21:47 UTC, rfay commented
How about starting apps one at a time that aren't running, snapshot them and then stop them? Snapshot auto-starts, right?

What your strategy here is is good, but most people who want a snapshot-all really want all to be done.

2022-04-04 15:19 UTC, FLeudts commented
One issue that could then exist is that it is possible to have projects without a DB. If they are started and the snapshot is tried it would fail again? In my usecase I had projects that weren't started because of this issue.

2022-04-06 05:58 UTC, rfay commented
@FLeudts is right, if `omit_containers[db]` then there's nothing to be done, and the app.Snapshot() fails with
```
Failed to snapshot j: unable to snapshot database,
your db container in project j is not running.
Please start the project if you want to snapshot it.
If deleting project, you can delete without a snapshot using
'ddev delete --remove-data --yes',
which will destroy your database
```

This isn't a bug with this PR, but it wouldn't do any harm to have app.Snapshot() output a message saying "not snapshotting because no database" and return nil.

2022-04-06 06:11 UTC, rfay requested changes
This works well and looks fine, thanks. Just the comments in https://github.com/drud/ddev/pull/3749#issuecomment-1089852818

2022-04-07 11:07 UTC, mikebarkas commented
I will make the requested changes. Thanks for your feedback.

2022-04-08 19:42 UTC, mikebarkas commented
Update

- I checked for omittedContainers before app.Snapshot. I don't think we should start an app and then try app.Snapshot if omit_container[db]
- I changed util.Failed to util.Warning so the snapshots will continue even if one fails. I colorized the warning message to red

2022-04-09 12:15 UTC, mikebarkas commented
Restarted `buildkite/ddev-macos-m1`

2022-05-01 19:57 UTC, rfay commented
Rebased. Should get it in shortly, thanks!

2022-05-02 21:12 UTC, merged