Add interactive project selection to start and stop command
drud/ddev pull request #3760
Opened 2022-04-13 16:50 UTC by cmuench

## The Problem/Issue/Bug: 
As a user I want to start a project by name. If the current working dir is not the project root, then I need to know the project name. Then I have to use `ddev list` to find the right name. Developers are lazy. So they have to copy the name to the clipboard.

## How this PR Solves The Problem: 
Provide an interactive selection of the project by adding a parameter `-s` to the `start` and `stop` command.

## Manual Testing Instructions:
Run `ddev start -s` or `ddev stop -s`

## Automated Testing Overview:
There are two new function in ddevapp.
- `ddevapp.ExtractProjectNames`
- `ddevapp.GetInactiveProjects`

There is a new file util_test.go which covers both new functions.
For the interactive command is currently no test available, because I do not know how we can test it.

## Related Issue Link(s):

## Release/Deployment notes:

2022-04-13 20:33 UTC, rfay commented
Thanks for this! I won't be able to look at it for a couple of weeks. On Camino de Santiago in Spain with only a phone.

2022-04-14 00:19 UTC, tyler36 commented
Wow! What a great idea. Works well

## Test
- Open PR in Gitpod
- Using the browse panel, search for "easy" to confirm site working
- Stop DDEV 

```shell
$ ddev stop
Container ddev-d9simple-db  Removed 
Container ddev-d9simple-web  Removed 
Network ddev-d9simple_default  Removed 
```
- Using the browse panel, search for "easy" and get expected 8080 error
- move to different directory

```shell
mkdir ../laravel
cd ../laravel
```

- attempt to start DDEV

```shell
gitpod /workspace/laravel $  ddev start
Failed to get project(s): could not find a project in /workspace/laravel
```

- Start d9simple project with new command

```shell
gitpod /workspace/laravel $ ddev start -s
The ddev-ssh-agent container has been removed. When you start it again you will have to use 'ddev auth ssh' to provide key authentication again.
Search: █
Projects:
  ▸ d9simple
Starting d9simple...
...
Successfully started d9simple
Project can be reached at https://8080-cmuench-ddev-2dawctvhsvj.ws-us39a.gitpod.io
```

- Using the browse panel, search for "pasta" to confirm site working
- attempt to stop DDEV with new command

```shell
gitpod /workspace/laravel $ ddev stop -s
✔ d9simple
Container ddev-d9simple-db  Removed 
Container ddev-d9simple-web  Removed 
Network ddev-d9simple_default  Removed 
```

- attempt to stop when no project is running

```shell
gitpod /workspace/laravel $ ddev stop -s
No project is currently running
```

2022-04-14 05:05 UTC, cmuench commented
> Thanks for this! I won't be able to look at it for a couple of weeks. On Camino de Santiago in Spain with only a phone.

There is not pressure here.
Enjoy your time in Spain.

2022-05-02 13:06 UTC, rfay commented
Rebased

2022-05-11 23:09 UTC, rfay requested changes
Rebased. I didn't figure out why the new TestGetInactiveProjects() is failing in our buildkite context (and I imagine now in the github tests as well).

2022-05-13 16:21 UTC, cmuench commented
@rfay buildkit job is now running for 15h. Seems something broken.

2022-05-26 20:33 UTC, rfay approved these changes
I feel lazy today, but since we all like this and it looks good, let's go with it.

2022-05-27 03:52 UTC, merged