Set permissions for GitHub actions
drud/ddev pull request #3763
Opened 2022-04-14 00:02 UTC by nathannaveen

- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions

https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)

 Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.

Signed-off-by: nathannaveen <42319948+nathannaveen@users.noreply.github.com>

2022-05-02 14:52 UTC, rfay commented
Thanks for this @nathannaveen - 

I'm still no expert at github workflows. But I do note from [update doc](https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/#:~:text=GitHub%20Actions%20now%20lets%20you,token%20when%20a%20job%20completes) that

> Pull requests from public forks are still considered a special case and will receive a read token regardless of these settings

So since all work on ddev is done with public forks.. does that make this PR irrelevant?

Thanks so much for your careful review of this. I've spent some time reviewing the difference between `pull_request` and `pull_request_target` this morning and am still a bit hazy, but it doesn't seem like we're necessarily doing the right thing in each case.

2022-05-02 14:55 UTC, nathannaveen commented
> Thanks for this @nathannaveen -
> 
> I'm still no expert at github workflows. But I do note from [update doc](https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/#:~:text=GitHub%20Actions%20now%20lets%20you,token%20when%20a%20job%20completes) that
> 
> > Pull requests from public forks are still considered a special case and will receive a read token regardless of these settings
> 
> So since all work on ddev is done with public forks.. does that make this PR irrelevant?
> 
> Thanks so much for your careful review of this. I've spent some time reviewing the difference between `pull_request` and `pull_request_target` this morning and am still a bit hazy, but it doesn't seem like we're necessarily doing the right thing in each case.

I will let you decide, thanks!

2022-05-02 15:33 UTC, rfay commented
Still interested in our opinion, and why this piqued your interest. I assume you're a ddev user and were studying the workflow...

2022-05-13 14:46 UTC, rfay requested changes
This all looks great, and thanks for taking the initiative to do it. I've spent more time with GITHUB_TOKEN and permissions now thanks to you. I do think the one item is superfluous, so please take a look.

2022-05-13 14:46 UTC, rfay commented on .github/workflows/master-build.yml
> +      contents: read  # for actions/checkout to fetch code
```suggestion
```

This section is superfluous because you set it globally above, right?

2022-05-13 21:52 UTC, nathannaveen commented
> This all looks great, and thanks for taking the initiative to do it. I've spent more time with GITHUB_TOKEN and permissions now thanks to you. I do think the one item is superfluous, so please take a look.

Thanks! I accepted the request!

2022-05-14 17:18 UTC, rfay commented on .github/workflows/master-build.yml
> +      contents: read  # for actions/checkout to fetch code
All you had to do was click "Commit suggestion" on this :)

2022-05-14 17:20 UTC, rfay approved these changes
Thanks!

2022-05-14 20:49 UTC, merged