Web container depends on db container, fixes #3702
drud/ddev pull request #3858
Opened 2022-05-20 20:13 UTC by mikebarkas

## The Problem/Issue/Bug:
Web container should depend on db container readiness unless omit_containers

## How this PR Solves The Problem:
This adds a `depends_on` for the web container if no `omit db`

## Manual Testing Instructions:
Start a ddev in a new project, look in the `.ddev-docker-compose-full.yaml `file

## Automated Testing Overview:

No tests added

## Related Issue Link(s):
#3702 

## Release/Deployment notes:

N/A

2022-05-20 21:17 UTC, rfay commented
I'm trying to figure out a manual test that will show this well. A huge DB might do it, may be able to see how long it takes for db container to get ready in that case, and keep a curl going in the db container.

2022-05-22 00:21 UTC, rfay commented
I think this is causing macos-nfs to fail (more),  https://buildkite.com/drud/ddev-macos-use-nfsmount/builds/5108#bbcfd70f-75f9-474e-9604-dc494f7b0946 

I've seen this plenty of times with NFS, never understood it. Essentially, the composer.json doesn't get there in time to be used, which is probably an NFS failure. But we're seeing it here on 3 different test runners. 

Line 90 is this:
```go
		args = []string{"composer", "create", "--prefer-dist", "--no-dev", "--no-install", "psr/log:1.1.0"}
		out, err = exec.RunHostCommand(DdevBin, args...)
		assert.NoError(err, "failed to run %v: err=%v, output=\n=====\n%s\n=====\n", args, err, out)
```

It's got --no-install even, so it's not trying to do a lot. 

It will be interesting to see if it's recreatable in local with NFS. And of course this may just be random behavior, because it's been seen before. It's possible that slightly slower startup could affect this, or that the exec that's done doesn't respect the startup, etc.

2022-05-22 11:47 UTC, mikebarkas commented
Perhaps the complexity this is introducing isn't worth the change?
Maybe a better approach is, recommend someone to add an override compose file as needed for their project?

2022-05-22 14:08 UTC, rfay commented
I don't consider this very complex. Just want to understand what might be happening. Would be lovely to understand why the composer.json doesn't exist when it needs to, since that's been an intermittent problem for years, and especially (only?) with NFS.  Since this one seem to fail every single time with macOS/NFS it may be a lovely situation to learn from. I'll spend a little time with it, and of course you're welcome to also. And I'm still in search of manual testing that will show the scope of this change and the impact on real users.

2022-05-22 16:45 UTC, rfay commented
To test the behavior, I created an alternate healthcheck.sh for the database container (mysql/mariadb) that waits 15s before declaring the db container healthy.  I put that in `.ddev/db-build`
Then I added a `.ddev/db-build/Dockerfile` with
```dockerfile
ARG BASE_IMAGE
FROM $BASE_IMAGE
COPY healthcheck.sh /
RUN chmod +x /healthcheck.sh
```

Then... `export PROJ=d9simple; while true; do date && echo "===== Web container" && docker inspect --format "{{json .State.Health.Log }}" ddev-$PROJ-web |jq -r last && echo "==== DB container" && docker inspect --format "{{json .State.Health.Log }}" ddev-$PROJ-db |jq -r last && sleep 1; done`

Do the `ddev start` in another windows.

That shows the health status of both containers, but you'll see that the web container has in fact been started and becomes healthy before the db container does. However, if you wait until `ddev start` completes to do things... it is behaving correctly waiting for both containers to be up. But I'm pretty sure that's true without this change.

2022-05-22 16:46 UTC, rfay requested changes
I don't think this accomplishes what we want yet, see my testing example. Looks like in https://github.com/compose-spec/compose-spec/blob/master/spec.md#depends_on we need to use the long form, so 
```yaml
    depends_on:
      db:
        condition: service_healthy
```

2022-05-23 04:14 UTC, rfay commented
@mikebarkas don't worry about the NFS test failure right now. It's lovely that it's predictable, I can reproduce it, have no idea why it would be impacted by the depends_on here. 

I've been experimenting with the various things in 
* https://github.com/composer/composer/issues/9627
where composer added an environment variable `COMPOSER_RUNTIME_ENV=virtualbox` to deal with things just like this, doing a sleep to let the filesystem catch up. But I haven't been able to solve the problem using either that or the suggested dummy unzip command in that issue.

2022-05-23 13:22 UTC, rfay commented
Always try a `ddev start && ddev launch`  :)

The syntax is yaml object syntax, not array syntax, 

```
    depends_on:
      db:
        condition: service_healthy
```

2022-05-23 14:48 UTC, rfay commented
We've all done it! :)

2022-05-23 15:46 UTC, rfay commented
It's wonderful how consistent that with-NFS failure is, but I'm completely baffled how it relates to this change, and although I've chased a lot of angles with it here I haven't found anything that affects it. And since I can't recreate it with manual testing (which works fine) I'm a bit at a loss.

2022-05-23 18:08 UTC, rfay commented
And now, unlike last time, we have the test failure on Windows NFS as well :( How in the world could this be affected by this PR... ??? :)

2022-05-23 18:24 UTC, rfay approved these changes
This seems to work perfectly now, tested on Windows WSL2 with Ubuntu 22.04. Using the (edited recipe above - forgot the healthcheck link before) I see this:

```json
Mon May 23 12:20:54 PM MDT 2022
===== Web container
Template parsing error: template: :1:13: executing "" at <.State.Health.Log>: map has no entry for key "Health"
==== DB container
null
Mon May 23 12:20:56 PM MDT 2022
===== Web container
Template parsing error: template: :1:13: executing "" at <.State.Health.Log>: map has no entry for key "Health"
==== DB container
null
Mon May 23 12:20:57 PM MDT 2022
===== Web container
null
==== DB container
{
  "Start": "2022-05-23T12:20:42.002494-06:00",
  "End": "2022-05-23T12:20:57.1979635-06:00",
  "ExitCode": 0,
  "Output": "waiting a little bit before declaring healthyhealthy"
}
Mon May 23 12:20:59 PM MDT 2022
===== Web container
{
  "Start": "2022-05-23T12:20:59.218305-06:00",
  "End": "2022-05-23T12:20:59.3281947-06:00",
  "ExitCode": 1,
  "Output": "phpstatus: FAILED /var/www/html: OK mailhog: FAILED "
}
==== DB container
{
  "Start": "2022-05-23T12:20:42.002494-06:00",
  "End": "2022-05-23T12:20:57.1979635-06:00",
  "ExitCode": 0,
  "Output": "waiting a little bit before declaring healthyhealthy"
}
Mon May 23 12:21:01 PM MDT 2022
===== Web container
{
  "Start": "2022-05-23T12:21:01.524198-06:00",
  "End": "2022-05-23T12:21:01.6891125-06:00",
  "ExitCode": 0,
  "Output": "phpstatus: OK /var/www/html: OK mailhog: OK "
}
==== DB container
{
  "Start": "2022-05-23T12:20:42.002494-06:00",
  "End": "2022-05-23T12:20:57.1979635-06:00",
  "ExitCode": 0,
  "Output": "waiting a little bit before declaring healthyhealthy"
}
Mon May 23 12:21:03 PM MDT 2022
===== Web container
{
  "Start": "2022-05-23T12:21:01.524198-06:00",
  "End": "2022-05-23T12:21:01.6891125-06:00",
  "ExitCode": 0,
  "Output": "phpstatus: OK /var/www/html: OK mailhog: OK "
}
==== DB container
{
  "Start": "2022-05-23T12:20:42.002494-06:00",
  "End": "2022-05-23T12:20:57.1979635-06:00",
  "ExitCode": 0,
  "Output": "waiting a little bit before declaring healthyhealthy"
}
```

The web container doesn't start to come up until the db container is fully ready.

`ddev start` completes when both are ready.

Will continue trying to figure out the NFS situation. Thanks for this!

2022-05-24 15:00 UTC, rfay commented
Thanks, I'm not sure it's actually changing "performance" as opposed to giving a realistic view of readiness, but I'm also interested in what you're seeing. Your result would seem to indicate that the db container is taking a really long time to come up, or that the go code that waits for it is doing something wrong. 

Could you check the results of this with a plain vanilla project (`ddev debug test` for example) and see what you see. 

I'm actually not used to `ddev start` taking anywhere near as long as you're seeing. You're on Linux right? I would expect 10-30s.

Oh, you're doing 10 restarts, so that's reasonable. I thought you were doing one restart.

2022-05-24 16:39 UTC, jonaseberle commented
`restart` overemphasizes the effect by also showing docker-compose safely tearing down the project without breaking the constraints. We lose some parallel execution that docker-compose can take advantage of if no constraints are there.

```
ddev poweroff
time for i in $(seq 5); do ddev debug test; done
```
I see no real difference:
main: 1m57s
this PR: 2m2s

@rfay are you sure we are testing the right thing here? Looking into the `ddev debug test` container does not show the `depends_on`. My test project shows it.

```
# with this PR:
ddev debug test
debugContainer=$(docker ps -q --filter=name='ddev-tryddevproject-.*-db')
docker inspect $debugContainer \
  | jq -r '.[].Config.Labels'

mkdir /tmp/a && cd /tmp/a
ddev config --auto
ddev start
# outputs:   "com.docker.compose.depends_on": "db:service_healthy",
docker inspect ddev-a-web \
  | jq -r '.[].Config.Labels'
ddev delete -Oy
```

2022-05-24 20:45 UTC, jonaseberle commented
I spotted my error ;) `--filter=name='ddev-tryddevproject-.*-db'` -> I checked the `db` container ...

Sorry for the fuss.

2022-05-24 20:45 UTC, jonaseberle approved these changes

2022-05-24 22:42 UTC, rfay commented
Rebased and excluded TestCmdComposer when running NFS-based tests. I've always thought this had to be a composer/filesystem bug, and after following the linked issues I think so more... but I can't sort it out, and I can't get composer to output enough verbosity to help me.

2022-05-25 03:05 UTC, merged

2022-05-25 03:05 UTC, rfay commented
Thanks for this!

2022-08-08 17:05 UTC, rfay commented
Unfortunately, this leads to some unfortunate behavior from docker-compose, see 
* https://github.com/docker/compose/issues/9732

The result is that docker-compose can just hang if the db container exits early. 

I think I'll have to revert at least part of this PR.