[docs] Standardize docs menu items
drud/ddev pull request #3891
Opened 2022-06-06 12:20 UTC by CollierCZ

## The Problem/Issue/Bug:

As part of an audit of the docs, this PR focuses on the left menu items and making sure they follow a standard pattern so readers can more easily scan for what they want to find.

## How this PR Solves The Problem:

Uses verbs and a single way of referring to DDEV to make comparisons more clear.

## Automated Testing Overview:

This only changes the docs, so shouldn't require other testing

2022-06-07 23:27 UTC, rfay requested changes
Minor suggestions, at least one that you can just click the button to commit. 

I ran this with `mkdocs serve` and looked at it and it seemed like a big improvement.

I found that spellchecking wasn't being done beyond first level of docs, so you may have to rebase this to get it in after that one goes in. 

Thanks so much! What a great start to cleanup.

I worry always that we'll change a URL that's externally known, but at least here the internal links should be checked during tests.

2022-06-08 02:04 UTC, rfay commented
BTW I just read the [goreleaser docs](https://goreleaser.com/intro/) from start to finish on my phone. So nice, such good flow. Would love to end up with nested sections like that. And they're using our same mkdocs material theme.

2022-06-08 03:10 UTC, rfay commented
Rebased. I figured since I made the mess I should do the rebase.

2022-06-08 06:32 UTC, CollierCZ commented on docs/users/topics/webserver.md
> +It's a common practice to set up HTTP to TLS redirects in the .htaccess file, which leads to issues with the DDEV proxy setup. The TLS endpoint of a DDEV project is always the `ddev-router` container
Thanks!

2022-06-08 06:46 UTC, CollierCZ commented
The GoReleaser docs definitely look clean. I think something similar could be possible in time, for sure. Just needs time to do a deeper run. Was hoping to get quicker improvements this time through and come back to it.

2022-06-08 21:28 UTC, merged

2022-06-08 21:28 UTC, rfay commented
Thanks!