Use bullseye-slim for ssh agent container (#3250)
drud/ddev pull request #3931
Opened 2022-06-21 22:13 UTC by mikebarkas

## The Problem/Issue/Bug:
To update to bullseye-slim

## How this PR Solves The Problem:
Changes the version for ddev-ssh-agent container

## Manual Testing Instructions:
Poweroff ddev and removed ssh agent images
Start a ddev project and should see pulling the new image

## Automated Testing Overview:

n/a

## Related Issue Link(s):

## Release/Deployment notes:

2022-06-21 22:37 UTC, rfay requested changes
Don't forget you have to push new version and bump the version in versionconstants.go. Do you want to push to your own dockerhub account for now for testing, or want me to push it for you? Does it test OK?

(Edit: I see in the issue you tested it manually, even pushed a personal image. It's OK to go forward with that in this PR, and we'll change it before pulling)

2022-06-22 17:34 UTC, rfay commented
Happy to meet with you tomorrow, but you don't need me to push this forward. You already pushed an image in your testing, just reference that image in versionconstants.go so this actually gets tested.

2022-06-22 21:12 UTC, rfay approved these changes
Thanks, good to go after updating official tag and after it passes tests and manual testing.

2022-06-23 00:23 UTC, rfay commented
Oddly, looks like it fails on circleci only, https://app.circleci.com/pipelines/github/drud/ddev/6748/workflows/b8edc668-9cd1-4eab-91fe-a369f3d6176c/jobs/38161

It's in the layer-adding user/group stuff, 

`        	            	#6 [2/2] RUN (groupadd --gid 1000 "circleci" || groupadd "circleci" || true) && (useradd  -l -m -s "/bin/bash" --gid "circleci" --comment '' --uid 1000 "circleci" || useradd  -l -m -s "/bin/bash" --gid "circleci" --comment '' "circleci" || useradd  -l -m -s "/bin/bash" --gid "1000" --comment '' "circleci")
        	            	#6 0.232 standard_init_linux.go:219: exec user process caused: exec format error
        	            	#6 ERROR: executor failed running [/bin/sh -c (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username" || useradd  -l -m -s "/bin/bash" --gid "$gid" --comment '' "$username")]: exit code: 1
        	            	------
        	            	 > [2/2] RUN (groupadd --gid 1000 "circleci" || groupadd "circleci" || true) && (useradd  -l -m -s "/bin/bash" --gid "circleci" --comment '' --uid 1000 "circleci" || useradd  -l -m -s "/bin/bash" --gid "circleci" --comment '' "circleci" || useradd  -l -m -s "/bin/bash" --gid "1000" --comment '' "circleci"):
        	            	#6 0.232 standard_init_linux.go:219: exec user process caused: exec format error
        	            	------
        	            	', stderr='failed to solve: executor failed running [/bin/sh -c (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username" || useradd  -l -m -s "/bin/bash" --gid "$gid" --comment '' "$username")]: exit code: 1'
        	Test:       	TestGetLocalHTTPResponse
`

2022-06-23 00:44 UTC, rfay commented
`ddev start` with this just fails on circleci. Doesn't have to be in that test.

2022-06-23 00:48 UTC, rfay commented
Oh, the problem is you didn't push both images. You only pushed an amd64 image, no idea how the mac m1 tests could have worked. https://hub.docker.com/r/mikebarkas/ddev-ssh-agent/tags

Please use `make push` to push. `make push DOCKER_REPO=mikebarkas/ddev-ssh-agent VERSION=3250-test`

2022-06-27 21:22 UTC, mikebarkas commented
I see the make file does multiple build archs, apologize I didn't realize that would break tests.

I tried the make push
```
make push DOCKER_REPO=mikebarkas/ddev-ssh-agent VERSION=3250-test
docker buildx build --push --platform linux/amd64,linux/arm64 -t mikebarkas/ddev-ssh-agent:3250-test --label "build-info=mikebarkas/ddev-ssh-agent:3250-test commit=v1.19.1-120-g6d3f7096 built $(date) by $(id -un) on $(hostname)" --label "maintainer=DDEV <randy@randyfay.com>"  .
unknown flag: --push
See 'docker --help'.
```

I am not using Docker Desktop, I am using Colima and homebrew docker.

I will try to install the buildx binary, maybe that will fix "unknown flag: --push"

2022-06-27 21:59 UTC, rfay commented
Thanks @mikebarkas - Yes, you have to do it in the ddev-webserver directory. Maybe that will get easier someday!

2022-06-27 23:24 UTC, mikebarkas commented
I learned some about buildx and docker context. I made a multi-arch builder with a docker image https://github.com/multiarch/qemu-user-static

I managed to push to docker hub. Thanks for your help.
https://hub.docker.com/r/mikebarkas/ddev-ssh-agent/tags

2022-06-28 00:10 UTC, rfay commented
Nice work, thanks! Why don't you push a dummy commit to run all the tests again, just `git commit -m "dummy commit for tests" --allow-empty`

2022-06-29 03:38 UTC, rfay approved these changes
Manually tested, worked fine. Pushed it as drud/ddev-ssh-agent. Ready to pull after tests. Thanks!

2022-06-29 21:27 UTC, merged

2022-06-29 21:27 UTC, rfay commented
Thanks @mikebarkas !