Improve documentation on how to contribute to the documentation
drud/ddev pull request #4000
Opened 2022-07-15 08:14 UTC by mikesnoeren

## The Problem/Issue/Bug:
- The documentation on how to contribute to the documentation wasn't really clear.
- The docker command to serve the documentation locally was missing some plugins.

## How this PR Solves The Problem:
- The documentation is now more clear.
- The docker command has been fixed.

2022-07-15 08:49 UTC, tyler36 commented
Perhaps we should remind people nicely to run a spellcheck (something I often forget 😢 )
Or instructions on how to manually trigger one (is this possible?)

2022-07-15 16:57 UTC, rfay commented
I see you did it with git this time as opposed to the web UI, congratulations! One little detail: I don't ever recommend using the "master" branch in your fork. Instead, use a branch named for the feature or bug you're working on. You'll never remember what "master" was. I usually name my branches like "yyyymmdd_short_description". That way they sort (I have many, many of them) and I can remember which one was for which. There's nothing wrong with what you did for this PR, just giving you a hint for the future.

2022-07-15 22:30 UTC, rfay requested changes
This is looking great! Now I'm going to stretch you by asking you to add another commit. 

When you make a PR, the PR docs are automatically created, for example, on yours. I think you should tell people about this.
<img width="975" alt="Improve_documentation_on_how_to_contribute_to_the_documentation_by_mikesnoeren_·_Pull_Request__4000_·_drud_ddev" src="https://user-images.githubusercontent.com/112444/179319480-bb62b30e-f6f7-4332-bf99-6619ded5a907.png">

2022-07-15 22:32 UTC, rfay commented
I'm sure you saw you have a couple of markdownlint problems at https://github.com/drud/ddev/runs/7361884798?check_suite_focus=true

You probably want to explain to people how to check with markdownlint as well before pushing? `make markdownlint`. 

I always do `make staticrequired` to get all of these, but it does mean installing those tools, and the Makefile tells how to install them.

2022-07-16 19:23 UTC, rfay commented
Congrats on getting the docs fixed!

2022-07-16 19:26 UTC, rfay requested changes
I just made one minor wording change; all you have to do is click the "commit" button in the PR.

2022-07-16 19:26 UTC, rfay commented on docs/content/developers/testing-docs.md
> +To start making changes you need to get a local copy of the DDEV documentation, we recommend you to [fork the DDEV repository](https://github.com/drud/ddev/fork) as that's where the documentation liv
```suggestion
To start making changes you'll need a local copy of the DDEV documentation, so [fork the DDEV repository](https://github.com/drud/ddev/fork) as that's where the documentation lives.
```

2022-07-16 21:32 UTC, merged

2022-07-16 21:32 UTC, rfay commented
Congratulations on your first PR, and number 4000!