fix: no need for SSH when using terminus token
drud/ddev pull request #4184
Opened 2022-09-06 14:49 UTC by shaal

## The Problem/Issue/Bug:

Terminus token allow users to connect to Pantheon without SSH.

## How this PR Solves The Problem:

This PR remove the check for SSH, and update documentation to reflect that change.

## Manual Testing Instructions:

## Automated Testing Overview:

## Related Issue Link(s):

## Release/Deployment notes:

2022-09-07 00:30 UTC, rfay requested changes
Sadly, this fails TestPantheonPush, can you take a look at that? https://app.circleci.com/pipelines/github/drud/ddev/7483/workflows/cd995e87-a7fa-4c5a-ab61-0678f92b17cf/jobs/39568

2022-09-07 02:52 UTC, shaal commented
Is seems that for `ddev pull` there's no need for SSH, but for `remote:drush` SSH is required.

2022-09-07 03:44 UTC, rfay commented
Would be cool if there's a better way!

2022-09-10 18:46 UTC, rfay commented
Closing, but sure open to a solution that works to accomplish this need.

One thing that you could do to pursue this is to put the ssh check into the push section instead of the auth section. Then you'd be happy. 

Why don't you give it a try?

Also, a technique that doesn't require drush rsync would be excellent.

2022-09-10 18:46 UTC, closed without merging