Optimize composer create to also work without --no-install
drud/ddev pull request #4273
Opened 2022-10-07 18:08 UTC by gilbertsoft

## The Problem/Issue/Bug:

`composer create-project` executes a `git clone` which is possible only into empty directories. Therefor the `ddev composer create` command was introduced to automatically bypass this problem and make the initialization easier for the user. This is achieved by running the `composer create-project` command automatically providing the directory argument and rsync the the files and folders from this directory afterwards to the project root directory. This can be very slow depending on the number of files and folders which must be synchronized and therefor using the `--no-install` option is suggested in many places to avoid issues and make the process faster but requires the user to run `ddev composer install` afterwards, once the `ddev composer create` command has finished. This workflow can be optimized again by handling the `--no-install` option automatically.

## How this PR Solves The Problem:

The `composer create` command now checks if the `--no-install` option is provided by the user. If not, it's now added by default and once the rsync is completed, `composer install` is called afterwards. This makes the project initialization easier.

## Manual Testing Instructions:

## Automated Testing Overview:

## Related Issue Link(s):

## Release/Deployment notes:

2022-10-07 18:10 UTC, rfay reviewed
I like it!

2022-10-07 19:24 UTC, gilbertsoft commented
> I like it!

Have to handle the options properly, some must be used for the install too.

2022-10-07 22:13 UTC, gilbertsoft commented
Done. Hope, all tests pass properly :)

2022-10-08 00:16 UTC, rfay commented
This is going to be great. It's too late in the v1.21.2 cycle though, so it can get in early after release and people will be using it then before v1.21.3 or v1.22

2022-10-08 12:36 UTC, gilbertsoft commented
There are potentially more cases in the quick start to change. So far I've only changed what works for sure. Other cases must be tested properly....

2022-10-14 14:45 UTC, rfay requested changes
This is awesome, a huge step forward. 

* Would it be possible for us to now use the command `ddev composer create-project` since it will actually work pretty well?
* I think we should fix up the "on the way" statements so it outputs "Doing composer create-project --no-install <args>" and then "Moving composer.json to project root" and then "Running `composer install <args>`". Probably already does that last one well enough.

Wonderful and awesome! Best thing that's happened to this since the beginning. Thanks!

2022-10-25 00:58 UTC, rfay commented
Rebased and fixed minor conflict.

2022-10-26 13:26 UTC, rfay commented
Rebased again.

2022-10-26 13:33 UTC, rfay approved these changes
Brilliant approach, well done. Big benefit. Thanks!

2022-10-26 13:34 UTC, merged

2022-12-02 18:23 UTC, rfay commented
This causes the laravel quickstart to fail, at least colima/macOS/mutagen.  It seems the create does more work than we usually expect before everything is copied over.

```
Executing composer command: [composer create-project --prefer-dist laravel/laravel --no-install /tmp/LPEgOF]

Creating a "laravel/laravel" project at "/tmp/LPEgOF"
Installing laravel/laravel (v9.3.12)
  - Installing laravel/laravel (v9.3.12): Extracting archive
Created project in /tmp/LPEgOF
> @php -r "file_exists('.env') || copy('.env.example', '.env');"
> @php artisan key:generate --ansi
PHP Warning:  require(/tmp/LPEgOF/vendor/autoload.php): Failed to open stream: No such file or directory in /tmp/LPEgOF/artisan on line 18

Warning: require(/tmp/LPEgOF/vendor/autoload.php): Failed to open stream: No such file or directory in /tmp/LPEgOF/artisan on line 18
PHP Fatal error:  Uncaught Error: Failed opening required '/tmp/LPEgOF/vendor/autoload.php' (include_path='.:/usr/share/php') in /tmp/LPEgOF/artisan:18
Stack trace:
#0 {main}
  thrown in /tmp/LPEgOF/artisan on line 18

Fatal error: Uncaught Error: Failed opening required '/tmp/LPEgOF/vendor/autoload.php' (include_path='.:/usr/share/php') in /tmp/LPEgOF/artisan:18
Stack trace:
#0 {main}
  thrown in /tmp/LPEgOF/artisan on line 18
Script @php artisan key:generate --ansi handling the post-create-project-cmd event returned with error code 255
Failed to create project:exit status 255, stderr=
```

2022-12-05 00:04 UTC, tyler36 commented
Not sure waht exactly you want to me check:

## Test

```shell
$ ddev --verion
ddev version v1.21.2-4-ga5403f9f

$ ddev config --project-type=laravel --docroot=public --create-docroot
...
Configuration complete. You may now run 'ddev start'. 

$ ddev start
Successfully started ga5403f9f 

$ ddev composer create-project --prefer-dist --no-install --no-scripts laravel/laravel
'ddev composer create-project' is unsupported. Please use 'ddev composer create'
for basic project creation or 'ddev ssh' into the web container and execute
'composer create-project' directly.

$ ddev ssh
$ composer create-project --prefer-dist --no-install --no-scripts laravel/laravel
Created project in /var/www/html/laravel

# Note: Laravel is installed in a subdirectory instead of current directory.

$ ls -a
.  ..  .ddev  laravel  public

```