Update quickstart.md
drud/ddev pull request #4314
Opened 2022-10-19 15:04 UTC by flynnt

## The Problem/Issue/Bug:
The original documentation related to changing where the `craft` executable is located in CraftCMS projects was slightly misleading as it implied you could make this change via and `.env` file.

## How this PR Solves The Problem:
This PR updates the docs to show how to provide this variable via DDEV's documented methods for providing environment variables to containers.

## Manual Testing Instructions:
Set up a CraftCMS project where the Craft application lives in a subdirectory. Follow the docs to set the location of the `craft` executable. Restart your project and test that `ddev craft` works.

## Related Issue Link(s):
https://github.com/drud/ddev/issues/4309

2022-10-19 23:37 UTC, rfay approved these changes
Thanks!

2022-10-19 23:37 UTC, rfay approved these changes
Thanks!

2022-10-20 01:37 UTC, khalwat approved these changes
Perfect, thank you for the correction!

2022-10-20 18:06 UTC, mattstein commented on docs/content/users/quickstart.md
> +    If you have Craft CMS installed in a sub-directory of your project, in order for `ddev craft` to work, you will need to change the location of the `craft` executable by providing the `CRAFT_CMD_R
CraftCMS → Craft CMS:

```suggestion
    If you have Craft CMS installed in a sub-directory of your project, in order for `ddev craft` to work, you will need to change the location of the `craft` executable by providing the `CRAFT_CMD_ROOT` environment variable to the web container in your project. For example, if your directory structure is `my-craft-project/app`, where Craft CMS is installed in `app`, then you would apply `ddev config --web-environment-add=CRAFT_CMD_ROOT=./app`. `CRAFT_CMD_ROOT` defaults to `./`, the project root directory. Run `ddev restart` after applying this change.
```

2022-10-20 18:06 UTC, mattstein requested changes
Thanks for this clarification! Just needs one space.

2022-10-25 17:23 UTC, mattstein approved these changes
Just realized we’re waiting on me to review that space. Apologies, and thanks again!

2022-10-26 13:21 UTC, merged