upload_dir support in Craft CMS, fixes #4302
drud/ddev pull request #4317
Opened 2022-10-20 15:10 UTC by rfay

## The Problem/Issue/Bug:

* #4302 

## How this PR Solves The Problem:

* Remove the wired upload_dir
* Remove the wired docroot (seems inappropriate? DDEV will autodetect, and people should be able to override?)
* Support specifying upload_dir in tests

## Manual Testing Instructions:

- [ ] `ddev config --upload-dir=files` on a craft project and see if it works with mutagen and `ddev start` - it should not warn.

2022-10-20 15:23 UTC, khalwat requested changes
So it looks good... the wired `web/` is set that way because that's what the default Craft CMS project sets is set to:

https://github.com/craftcms/craft

So I think in this case, it's a sane default, and eliminates having to specify the `--docroot=web` for every project. This is a case where Craft does have a baked in default.

If DDEV will auto-detect `web/` then sure, it can be removed.

That's assuming the override via `.yaml` works as expected.

The rest of it looks good, though!

2022-10-20 15:24 UTC, rfay commented
There is no need to set `--docroot=web` unless the code does not yet exist. That's the case in the composer-build quickstart. It will be autodetected otherwise. 

But people certainly may put the project in a subdir or have a different docroot, and the existing code would have blown away their configuration I think, right?

2022-10-20 15:27 UTC, khalwat commented
@rfay okay I didn't realize that DDEV would auto-detect `web/` if so then I agree, it's redundant/pointless.

As for the subdir, I'm assuming the check that was in there `if app.Docroot == ""` works, because people are using it (see recent docs PR).

But anyway yeah moot point if DDEV auto-detects `web/` regardless! Looks good!

2022-10-26 03:18 UTC, rfay commented
tested with `ddev import-files` with upload_dir set; it imported properly. mutagen/mutagen.yml was properly edited.

2022-10-26 03:18 UTC, merged

2023-05-09 07:33 UTC, riconeitzel commented
I'm researching a upload_dir set behaviour and stumbled upon this issue. was part of the issue that upload_dir will always be a sub directory of the docroot (which should not be) or was that behaviour introduced here? From reading the code it doesn't look like.

2023-05-09 12:21 UTC, bencroker commented
@riconeitzel The issue here is that Craft can be configured with multiple local user-generated directories, so there’s little point in hard-coding any single `upload_dir`. Read more about the general issue at https://github.com/ddev/ddev/issues/4190.

2023-05-09 12:44 UTC, bencroker commented
@riconeitzel The issue here is that Craft can be configured with multiple local user-generated directories, so there’s little point in hard-coding any single `upload_dir`. Read more about the general issue at https://github.com/ddev/ddev/issues/4190.