[docs] Update QuickStart !
drud/ddev pull request #4320
Opened 2022-10-22 14:46 UTC by ibrah3m

## The Problem/Issue/Bug:
Update QuickStart in the Laravel section
## How this PR Solves The Problem:
Adding example explain how to make Git Clone
## Manual Testing Instructions:

## Automated Testing Overview:

## Related Issue Link(s):

## Release/Deployment notes:

2022-10-24 15:06 UTC, rfay commented
If you would add a link to the repo you created to demonstrate this it would help testers, because they could just use that, thanks!

Manual testing instructions are always helpful.

And as discussed in discord, you'll want to figure out how not to do 25+ commits for a few lines of docs update.

2022-10-24 15:46 UTC, rfay commented
Why did you close it? If you want to change it, as you know, you can just push new commits.

2022-10-24 16:12 UTC, ibrah3m commented
> Why did you close it? If you want to change it, as you know, you can just push new commits.
I'm, trying to delete the old commits

2022-10-24 16:28 UTC, rfay commented
You don't need to delete the old commits. It's not a problem here, I'm just encouraging you to learn how to do these things.

BTW, you could rebase into a single commit and then `git push --force` that commit. 

Reopening.

2022-10-24 16:29 UTC, rfay commented
When this gets pulled, the way we do it in this project is to do a "squash" into a single commit, so there are no technical problems with the fact that you have so many commits. It's just that it's not what you want to be doing going forward.

2022-10-24 16:35 UTC, ibrah3m commented
my knowledge with git not the good so IDK many things how it must be done

2022-10-24 16:40 UTC, rfay commented
You pushed no commits this time, so now it's an empty PR. 

Some things you can do:

```
git log
git diff upstream/master
git log upstream/master..
```

2022-10-24 17:38 UTC, rfay commented
Yay!

2022-10-24 17:45 UTC, ibrah3m commented
> Yay!

somehow, By going back in the reference I just copied the commit that has the last edits 😁.

2022-10-26 11:07 UTC, ibrah3m commented
> If you would add a link to the repo you created to demonstrate this it would help testers, because they could just use that, thanks!
> 
> Manual testing instructions are always helpful.
> 
> And as discussed in discord, you'll want to figure out how not to do 25+ commits for a few lines of docs update.

hello I'm back, could you please explain what 'add a link to the repo you created' mean exactly am I need to create a new laravel project and put the git link in the instructions or what?

2022-10-26 11:42 UTC, rfay commented
I hope that you created a sample Laravel repository (on github) for testing this PR. If you didn't please do. So I was asking you to give the link to that repo in the manual testing instructions.

2022-10-26 11:43 UTC, ibrah3m commented
> I hope that you created a sample Laravel repository (on github) for testing this PR. If you didn't please do. So I was asking you to give the link to that repo in the manual testing instructions.

done using the following repo 
https://github.com/ibrah3m/laravel

2022-10-26 11:57 UTC, ibrah3m commented
@rfay  check this out! I hope its matches the requirements.

2022-10-26 12:26 UTC, rfay commented
<img width="976" alt="_docs__QuickStart_Laravel_Git_Clone_by_ibrah3m_·_Pull_Request__4320_·_drud_ddev" src="https://user-images.githubusercontent.com/112444/198025654-6bdb9d84-83a1-447f-995e-42a4204afcf9.png">

2022-10-26 12:40 UTC, ibrah3m commented
> <img alt="_docs__QuickStart_Laravel_Git_Clone_by_ibrah3m_·_Pull_Request__4320_·_drud_ddev" width="976" src="https://user-images.githubusercontent.com/112444/198025654-6bdb9d84-83a1-447f-995e-42a4204afcf9.png">

gotcha ! done

2022-10-26 13:20 UTC, rfay requested changes

2022-10-26 13:20 UTC, rfay commented on docs/content/users/quickstart.md
> +            If yes, please use the following repo https://github.com/laravel/laravel.git
```suggestion
```

2022-10-26 13:20 UTC, rfay commented on docs/content/users/quickstart.md
> +        git clone https://github.com/ibrah3m/laravel.git my-laravel-app
```suggestion
        git clone <your-laravel-repo>
```

2022-10-26 13:20 UTC, rfay commented on docs/content/users/quickstart.md
> +        cd my-laravel-app
```suggestion
        cd <your-laravel-project>
```

2022-10-26 16:16 UTC, ibrah3m commented
@rfay is everything okay?

2022-10-26 16:52 UTC, rfay commented
Please be more patient. Remember that I have loads of things to work on. This will happen in its time. If it needs something I will ask. A PR like this might sometimes wait a week or two.

2022-10-26 17:16 UTC, ibrah3m commented
> Please be more patient. Remember that I have loads of things to work on. This will happen in its time. If it needs something I will ask. A PR like this might sometimes wait a week or two.

sure take your time

2022-10-31 17:20 UTC, rfay approved these changes
Thanks!

2022-10-31 17:20 UTC, merged

2022-11-01 21:12 UTC, ibrah3m commented
> Thanks!

thanks for merging