Ignore `.DS_Store` files
drud/ddev pull request #4337
Opened 2022-10-25 23:30 UTC by mattstein

## The Problem/Issue/Bug:

One might easily and accidentally commit those annoying macOS `.DS_Store` files to their commit, adding cruft to the project.

## How this PR Solves The Problem:

This uses the `.gitignore` file to prevent those from being noticed or committed by Git.

## Manual Testing Instructions:

🤔 Stage this change, then purposefully try to commit a file named `.DS_Store`. It’ll be trickier, at least.

## Automated Testing Overview:

n/a

## Related Issue Link(s):

Faintly related to #4188; came up during #4336.

## Release/Deployment notes:

n/a

2022-10-25 23:38 UTC, rfay approved these changes
Nothing wrong with that, but I gitignore stuff like that in global gitignore, I recommend to you as well. 

My global .gitignore:
```
.project
.buildpath
.settings
nbproject/
.idea
.DS_Store
db/db_*
docroot/core/phpunit.xml
docroot/drush
docroot/sites/simpletest
docroot/modules/contrib/devel
sites/default/files
*.orig
*.rej
.tarballs
```

2022-10-25 23:42 UTC, mattstein commented
Oh, that makes more sense! Thank you.

2022-10-26 00:03 UTC, tyler36 commented
Yes, a global `.gitignore` is definately great.

However, I think for a project like DDEV that recieves lots of contributions, it's helpful to have a project level one too.

2022-10-26 00:13 UTC, rfay commented
May want to add a couple more of those if we're doing this one.

2022-10-26 00:37 UTC, mattstein commented
I mean now that we’ve trained me to use a global file, I won’t be noticing whatever those other things are! 😅 🚀

2022-10-26 01:35 UTC, rfay commented
Another pro tip: Always use `git add -u` when choosing changes for a commit. Then look and see what might be left over with `git diff`. The leftover stuff is normally cruft, unless you explicitly added a file, in which case `git add <file>`.  If you use `git add -u` you'll almost never check in something you shouldn't have.

2022-10-26 03:23 UTC, rfay requested changes

2022-10-26 03:23 UTC, rfay commented on .gitignore
> +*.DS_Store
```suggestion
*.DS_Store
nbproject/
.idea
*.orig
*.rej
```

2022-10-26 10:16 UTC, merged