Set NFS wsize/rsize options for Ventura (Fixes #4122)
drud/ddev pull request #4359
Opened 2022-11-01 15:56 UTC by karlshea

## The Problem/Issue/Bug:

#4122 

## How this PR Solves The Problem:

Sets `wsize`/`rsize` to 32768

## Manual Testing Instructions:

See #4122 

## Automated Testing Overview:

@rfay unsure how you'd like to test. I've been using a 100MB zip file and running md5sum on it from inside a container, but I bet you don't want a 100MB object in the git repo 🙃

## Related Issue Link(s):

#4122, docker/for-mac#6544

## Release/Deployment notes:

Existing NFS volumes would need to be deleted/recreated to pick up the new options.

2022-11-01 16:15 UTC, karlshea commented
Looks like Docksal has a similar PR: docksal/docksal#1728

2022-11-01 17:34 UTC, rfay commented
Awesome! Should be easy to generate a large file. 

A quick manual test with bedrock with and without this showed that this solves at least the trivial problem.

But I think I'll just upgrade the test runners to Ventura, and that a clearer test. 

@karlshea could you please add more detail to https://github.com/docker/for-mac/issues/6544 explaining where the default values come from, where they come from in recent docker and macOS?

2022-11-01 18:01 UTC, rfay requested changes
Looking great. I think these two comments will improve it. If they break anything I'll fix it :)

2022-11-01 18:01 UTC, rfay commented on pkg/dockerutil/dockerutils_test.go
> +	volume, err := CreateVolume(testVolume, "local", map[string]string{"type": "nfs", "o": "addr=host.docker.internal,hard,nolock,rw,wsize=32768,rsize=32768",
Glad you discovered this; it wasn't right for some environments.
```suggestion
        nfsServerAddr, _ := dockerutils.GetNFSServerAddr()
	volume, err := CreateVolume(testVolume, "local", map[string]string{"type": "nfs", "o": fmt.Sprintf("addr=%s,hard,nolock,rw,wsize=32768,rsize=32768", nfsServerAddr),
```

2022-11-01 18:59 UTC, karlshea commented
> @karlshea could you please add more detail to [docker/for-mac#6544](https://github.com/docker/for-mac/issues/6544) explaining where the default values come from, where they come from in recent docker and macOS?

That's a good call, check out my latest reply because it's interesting. We're actually *lowering* the default values that Docker sets.

2022-11-01 19:54 UTC, rfay commented
Mac test runners are all upgraded to Ventura now.

2022-11-01 19:54 UTC, rfay commented
However, the standard mac check is shortcutted and doesn't test any of the CMSs that failed, like laravel.

2022-11-01 21:16 UTC, rfay commented
There are some problems being detected by tests now. I haven't been able to recreate them on my local machine, so obviously I have some fun ahead.

2022-11-01 21:42 UTC, karlshea commented
It looks like one of those is a command line tools issue—I had the same problem locally after upgrading, it seemed like softwareupdate didn't see it so I had to launch XCode to get it installed.

2022-11-01 22:04 UTC, rfay commented
Yeah, I think I got all those fixed.

2022-11-01 22:56 UTC, rfay commented
On macstadium-m1 we're seeing this: `o: "addr=,hard,nolock,rw,wsize=32768,rsize=32768"` (no IP address) which I'm sure is a result of the change I made to not fall back to host.docker.internal.

2022-11-01 23:42 UTC, rfay commented
It turned out I was testing with Colima, not Docker Desktop, which has different characteristics for determining the NFS server. That's why I couldn't demonstrate the problem. But when I used Docker Desktop it was easy to see.

2022-11-02 00:17 UTC, rfay commented
One request @karlshea - When you make a PR, make a branch first, so the branch name of your PR isn't "master". That will help *you* the next time you create a PR (because you won't be confused what branch is what) but it will help here because your PR having the name "master" confused the dickens out of buildkite, which kept killing off jobs in the upstream/master branch when new ones were started in this PR.

2022-11-02 01:55 UTC, karlshea commented
Ahhh sorry! Branches are my normal workflow but I forked and committed in a rush this time.
On Nov 1, 2022 at 7:17 PM -0500, Randy Fay ***@***.***>, wrote:
> One request @karlshea - When you make a PR, make a branch first, so the branch name of your PR isn't "master". That will help you the next time you create a PR (because you won't be confused what branch is what) but it will help here because your PR having the name "master" confused the dickens out of buildkite, which kept killing off jobs in the upstream/master branch when new ones were started in this PR.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-11-02 01:58 UTC, karlshea commented
I can retarget this PR if that would make getting the tests right easier?

2022-11-02 02:15 UTC, rfay commented
I found out the setting that prevents this in buildkite and now I actually understand why it exists!

2022-11-02 13:18 UTC, rfay commented
Didn't re-enable commented section in TestNFSMount and it got committed, so WSL2 was tested with NFS :(

2022-11-02 16:34 UTC, rfay commented
Thanks so much @karlshea for tracking this down. Very impressive work and very much appreciated. It looks like it's going to pass everything (that I messed up) now. Let me know when you think it's ready to pull. Then it will be easily accessible to people with `brew unlink ddev && brew install --HEAD --fetch-head ddev`

2022-11-02 17:48 UTC, merged