AUR: bring dependencies back to PKGBUILD recipe
drud/ddev pull request #4396
Opened 2022-11-22 10:05 UTC by stasadev

## The Problem/Issue/Bug:
After moving to GoReleaser, dependencies for AUR were lost.

## How this PR Solves The Problem:
Brings back missing `depends` and `optdepends`.
I moved `docker-compose` to `optdepends` because it is not required now.

## Manual Testing Instructions:
Check `PKGBUILD` for the options above in [ddev-bin](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ddev-bin) and [ddev-edge-bin](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ddev-edge-bin) after release.

## Automated Testing Overview:

## Related Issue Link(s):
https://github.com/drud/ddev/issues/3723

## Release/Deployment notes:

2022-11-22 14:12 UTC, rfay commented
Awesome, looks reasonable. I'll have to test an actual push.

2022-11-23 00:32 UTC, rfay commented
Took some work, but pushed to https://aur.archlinux.org/packages/rfay-test-ddev-edge-bin in https://github.com/rfay/ddev/actions/runs/3528130105

Please verify that package, thanks @stasadev

2022-11-23 00:54 UTC, rfay requested changes
Other than the removal of docker-compose from optional deps, I think this is fine. Would the `docker` package be the only docker provider one would ever expect to find on arch?

I tested with `yay -Syu rfay-test-ddev-edge-bin` and everything seemed to go fine.

2022-11-23 00:54 UTC, rfay commented on .goreleaser.yml
> +  - 'docker-compose: for use_docker_compose_from_path option'
```suggestion
```

docker-compose is *not* recommended.

2022-11-23 00:54 UTC, rfay commented on .goreleaser.yml
> +  - 'docker-compose: for use_docker_compose_from_path option'
```suggestion
```

Not recommended

2022-11-23 09:16 UTC, stasadev commented
Works as it should, thanks!

> Would the docker package be the only docker provider one would ever expect to find on arch?

This `depends=('docker')` looks for any package, that `provides=('docker')`, which is of course not limited to the `docker` package.

For Arch, this can be any of the following: `docker` (`docker-experimental-git`, `docker-git`, `rancher-desktop-git`, `podman-docker-git`, `docker-cli-bin`, `rancher-desktop`, `podman-docker`)

2022-11-23 14:26 UTC, rfay approved these changes
Thanks!

2022-11-23 14:27 UTC, rfay commented
I haven't looked at podman for some time, but it certainly wasn't interoperable with DDEV when I looked. docker-cli of course wouldn't meet the need alone. rancher-desktop did work last I tried.

2022-11-23 20:22 UTC, merged

2022-11-24 13:43 UTC, stasadev commented
I haven't tested these programs, the only thing I've tried is Docker Desktop for Arch, but it's a total mess, so I gave up.
Then I discovered another GUI for local docker, Portainer Community Edition (free version).
I'm using it now, it's pretty good. Can run as a docker image and has builds for Linux/Windows, not sure about macOS.

2022-11-24 14:04 UTC, rfay commented
Yeah, Docker Desktop for Linux just doesn't work right (yet?). Uses VirtioFS for it's filesharing and it's not consistent. Terrible stuff. I even put a detection into upcoming version to point out that it's not supported if people try to use it.