Improve custom configuration information message
drud/ddev pull request #4488
Opened 2022-12-23 00:06 UTC by skeemer

## The Problem/Issue/Bug:
Confusing error message with typo.

## How this PR Solves The Problem:
Improves the readability.

## Manual Testing Instructions:

## Automated Testing Overview:
N/A

## Related Issue Link(s):

## Release/Deployment notes:
This doesn't change how anything works.

2022-12-23 00:16 UTC, rfay requested changes
Thanks, I think this will do. Minor suggestion you can pull.

2022-12-23 00:16 UTC, rfay commented on pkg/ddevapp/config.go
> +		util.Warning("The custom configuration(s) are updated on restart.\nIf you don't see your custom configuration taking effect, run 'ddev restart'.")
```suggestion
		util.Warning("Custom configuration is updated on restart.\nIf you don't see your custom configuration taking effect, run 'ddev restart'.")
```

2022-12-23 15:53 UTC, rfay approved these changes
Thanks!

2022-12-23 15:55 UTC, rfay requested changes
Oh, unfortunately this breaks fragile 


```
Ensuring write permissions for TestPkgDrupal9
  | config_test.go:798:
  | Error Trace:	config_test.go:798
  | Error:      	"\x1b[33mUsing custom nginx configuration in /Users/testbot/tmp/ddevtest/TestPkgDrupal92850953183/.ddev/nginx_full/nginx-site.conf\x1b[0m\n\x1b[33mUsing nginx snippets: [/Users/testbot/tmp/ddevtest/TestPkgDrupal92850953183/.ddev/nginx/junker99.conf]\x1b[0m\n\x1b[33mUsing custom mysql configuration: [/Users/testbot/tmp/ddevtest/TestPkgDrupal92850953183/.ddev/mysql/collation.cnf]\x1b[0m\n\x1b[33mUsing custom PHP configuration: [/Users/testbot/tmp/ddevtest/TestPkgDrupal92850953183/.ddev/php/my-php.ini]\x1b[0m\n\x1b[33mCustom configuration is updated on restart.\nIf you don't see your custom configuration taking effect, run 'ddev restart'.\x1b[0m\n" does not contain "Custom configuration takes effect"
 ```

If you want to fix config_test.go:798 you can, otherwise let me know and I'll push it in there.

2022-12-27 23:28 UTC, rfay commented
Fixed test.

2022-12-27 23:28 UTC, rfay approved these changes

2022-12-27 23:29 UTC, mattstein approved these changes

2022-12-28 16:48 UTC, merged