Update phpstorm.md
drud/ddev pull request #4513
Opened 2023-01-02 23:26 UTC by jeroenimpres

Added a little note on finding the DDEV docker-compose file

## The Issue
I searched and searched after installing DDEV. I thought I should be prepared well and already install the plugin and appointing the right docker-compose file. This was before I did a `ddev start`.

## How This PR Solves The Issue
It might not solve, but maybe give someone like me a hint :-)

## Manual Testing Instructions

## Automated Testing Overview

## Related Issue Link(s)

## Release/Deployment Notes

2023-01-02 23:43 UTC, rfay commented
I kind of think they should have started a project before trying to integrate with PhpStorm in the first place?

2023-01-02 23:46 UTC, jeroenimpres commented
Well, maybe I am the only one then 😅 But it happened to me today.. I did a brew install first, read that there was a plugin and thought to myself: that might just be one handy thing to have before I start my project. And that's when I could not find the directory mentioned in the docs.

2023-01-02 23:50 UTC, rfay commented
I imagine you're not the only one, but maybe the idea "Start one first" should go higher.

2023-01-02 23:55 UTC, jeroenimpres commented
Ah thanks for the clarification, will do!

2023-01-02 23:57 UTC, jeroenimpres commented
I now put it in the requirements :-)

2023-01-03 22:16 UTC, rfay requested changes
Thanks!

2023-01-03 22:19 UTC, mattstein approved these changes

2023-01-03 22:25 UTC, merged

2023-01-03 22:25 UTC, rfay commented
Thanks @jeroenimpres !