Fix user queries for full path
drud/ddev pull request #4656
Opened 2023-02-15 20:44 UTC by gilbertsoft

## The Issue

In the two queries for a full path, "pull" is used instead of "full".

## How This PR Solves The Issue

"pull" is replaced by "full".

## Manual Testing Instructions

Run the two commands `import-db` and `import-files` to see if the query for the path is fine.

## Automated Testing Overview

## Related Issue Link(s)

## Release/Deployment Notes

2023-02-15 20:45 UTC, gilbertsoft commented
Thanks to @sbusemann for this finding!

2023-02-17 02:05 UTC, rfay requested changes
I don't believe that this is correct. I think it was intended to be "Pull path", but that was poor. It does *not* need to be "Full path", as a relative path is fine. Instead, we should change the prompt to "Path to import" or something like that.

2023-02-18 18:12 UTC, rfay commented
I'm not even convinced that this fmt.Print() is useful. The path has already been requested....

2023-02-23 02:37 UTC, rfay commented
@gilbertsoft please take a look at https://github.com/drud/ddev/pull/4656/commits/0871166f126669afc30c204697ad6c4a2af37a95 and see if it works for you.

2023-02-23 02:38 UTC, rfay approved these changes
I think this is right now, hope for @gilbertsoft approval.

2023-02-24 03:02 UTC, merged