Wrap diagnostic output into collapsed <details> block
drud/ddev pull request #4865
Opened 2023-05-03 14:20 UTC by MurzNN

## The Issue
We need to create a gist now to paste diagnostic information, that is too many actions for a regular user.

## How This PR Solves The Issue
This fix should add the pre-filled text to the diagnostic field.

## Manual Testing Instructions
Create a new issue and fill the diagnostic data.

## Automated Testing Overview

## Related Issue Link(s)
Fixes #4244

## Release/Deployment Notes

<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4865"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2023-05-03 14:45 UTC, rfay commented
IIRC this approach doesn't work in bug report template, but please try it in your own repo or fork to make sure.

2023-05-03 15:01 UTC, MurzNN commented
There was a whitespace problem, fixed now, here is the example bug: https://github.com/MurzNN/ddev/issues/7
Please check.

2023-05-03 20:09 UTC, rfay requested changes
Thanks, I think this is great. Minor suggestions you can accept (and preferably test in your fork too). I appreciate it. I think the last time this was attempted it didn't work out.

2023-05-03 20:09 UTC, rfay commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        [COPY-PASTE HERE THE DIAGNOSIC INFORMATION]
```suggestion
        [COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```

2023-05-03 20:09 UTC, rfay commented on .github/ISSUE_TEMPLATE/bug_report.yml
>          If you’re having trouble with DDEV, help us with context that will skip a bunch of questions:
```suggestion
        Whether you’re having trouble or not, help us with context that will skip a bunch of questions we'd have to ask afterwards:
```

2023-05-04 00:32 UTC, mattstein approved these changes

2023-05-04 13:08 UTC, merged